### ISSUE TITLE
Readme.txt Docs

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#10]
Add general readme.txt docs
- [x] - FAQ?
- [x] - Main Description
- [x] - Readme.txt validates
- [x] - Screenshots match readme
- [x] - Short Description
- [x] - Installation
- [x] - Changelog

**Comment by mpsparrow** [comment]
I need to get motoring on this. We can't update the plugin until the readme.txt is done.

**Comment by ronalfy** [comment]
If I have time, I'll take a crack at this.  I won't be able to do anything until this weekend though.

**Comment by mpsparrow** [comment]
For now, I will take a stab at it and let you know what the result is.

**Comment by mpsparrow** [comment]
I have been fairly busy. I was able to add a few things but not much. I will take a stab at it now.

**Comment by mpsparrow** [comment]
What do you think is the "Requires at least" version?

**Comment by ronalfy** [comment]
I would say to be safe 4.0.

**Comment by mpsparrow** [comment]
Ok, that's what I thought.

**Comment by mpsparrow** [comment]
Me cannot change that part in the short description. b95ed55beea181a38f9aa51d67aa9af558615cc3 it puts the short description over the maximum 150.

**Comment by mpsparrow** [comment]
That is why I changed it in 1e5cb89f8d26ab3c9abe5a378094bda72e433052

**Comment by mpsparrow** [comment]
Sorry, I mean b95ed55beea181a38f9aa51d67aa9af558615cc3

**Comment by mpsparrow** [comment]
Just fixed this in 1f7829dfa966f5cafa9e24483e52471316d7f43c. Re-worded it as to not remove the WordPress Multisite and keep it under 150.

**Comment by mpsparrow** [comment]
Do you think we need a FAQ?

**Comment by ronalfy** [comment]
How about we add one as we need to.

**Comment by ronalfy** [comment]
I'm thinking this is done.  Thoughts @mpsparrow ?

**Comment by mpsparrow** [comment]
Yah. We can add more in the upcoming versions.
