### ISSUE TITLE
Add active class 

### ISSUE THREAD

**Issue by roarytubbs** [easy-updates-manager/easy-updates-manager#107]
I need an .active class added to .dashboard-item-header. I need to be able to know when something is active or not. I'm not sure the current JS code is working properly of efficient for what I'm needing.

**Comment by ronalfy** [comment]
Thanks, I'll take a look shortly.

**Comment by ronalfy** [comment]
The active/inactives should be for the main plugin/theme tabs below. Can you (@roarytubbs) please explain in more detail what this will accomplish?

**Comment by ronalfy** [comment]
Fixed.
