### ISSUE TITLE
Unnecessary dashboard-item class

### ISSUE THREAD

**Issue by roarytubbs** [easy-updates-manager/easy-updates-manager#108]
There is still an unnecessary dashboard-item div wrapped around another dashboard-item div. I'm looking under "Plugin and Theme Updates".

<img width="533" alt="screen shot 2015-10-29 at 12 47 07 pm" src="https://cloud.githubusercontent.com/assets/1294345/10827140/53b60262-7e3b-11e5-828a-796f84081195.png">

**Comment by ronalfy** [comment]
Fixed https://github.com/easy-updates-manager/easy-updates-manager/commit/dc13a834e1f56fdd217351c5f18348596c5c8fbb
