### ISSUE TITLE
Remove Email Notifications

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#115]
Since the patch wasn't committed in 4.4, let's comment them out for a later release.

**Comment by ronalfy** [comment]
Changes are committed in the Dev Branch. Let's keep testing to make sure everything is good to go for a 5.4.2 release.

**Comment by mpsparrow** [comment]
Should we aim for a 5.4.2 or 5.5 release in conjunction with WordPress 4.4? WordPress 4.4 is scheduled to be released December 8, although I wouldn't be surprised if it gets delayed a week because 4.4 RC1 hasn't even been released yet.

**Comment by ronalfy** [comment]
I would say release when the first RC is dropped.

**Comment by mpsparrow** [comment]
I think the first RC is being dropped today.

> Let’s do a scrub to push through the remaining 4.4 tickets on ‎Wednesday‎, ‎November‎ ‎24‎, ‎2015‎ ‎03‎:‎00‎ ‎PM‎ ‎EST so we can get to RC tomorrow, Wednesday the 25th.

**Comment by mpsparrow** [comment]
RC is out. https://wordpress.org/news/2015/11/wordpress-4-4-release-candidate/

**Comment by ronalfy** [comment]
OK! Here we go.
