### ISSUE TITLE
Lets Resolve These Support Threads

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#116]
- [x] https://wordpress.org/support/topic/plugin-not-working-for-me-at-all?replies=3#post-7664510
- [ ] https://wordpress.org/support/topic/plugin-stopped-working-for-one-of-my-sites?replies=8

They both could very well be related.

**Comment by ronalfy** [comment]
I am utterly clueless why an automatic update wouldn't work. If they're not getting minor security fixes either, it means they are probably disabling updates somewhere else, via a wp-config option, or somewhere else.

**Comment by mpsparrow** [comment]
I am clueless as well.

**Comment by mpsparrow** [comment]
Seeing as we have no idea what is up with that one I am just going to close this.
