### ISSUE TITLE
The `update_core` parameter for `current_user_can()` causes fail for Godaddy Managed WP

### ISSUE THREAD

**Issue by lolux** [easy-updates-manager/easy-updates-manager#118]
Hello Matthew,

First off, thanks for this great plugin. I'm glad to see it gaining in popularity. Keep up the great work!

I am experiencing a fatal error (die: "User does not have sufficient permissions") after activation and then attempting to access the configuration page on my Godaddy Managed WP sites.

The cause of the issue is that the `update_core` parameter is used for a permissions check in `current_user_can()`; since GoDaddy (and possibly other managed hosts???) automatically disable that permission for admin-role users (presumably since the host itself handles all core updates), my admin user is blocked.

If I change all the instances of the `update_core` parameter to another admin-role capability such as `install_plugins`, the plugin works.

So, I suggest considering changing the parameter (or some other workaround) to accommodate managed WP hosting use cases such as GoDaddy Managed.

peace,
Laurence

**Comment by mpsparrow** [comment]
Thanks for letting us know about this issue you are experiencing. We appreciate your support for Easy Updates Manager.

@ronalfy: Can you look into this when you have time?

**Comment by ronalfy** [comment]
Yep, will do.

**Comment by ronalfy** [comment]
@lolux I'm working off of the dev branch, but we plan to merge into the trunk branch soon once WordPress 4.4 RC1 rolls out.

I got this working locally and it seemed fine: https://github.com/easy-updates-manager/easy-updates-manager/commit/ff511dee916761e27925cd5b38a2c6c4dd0b23ff

**Comment by mpsparrow** [comment]
@lolux: We rolled out this in Easy Updates Manager 5.4.2 which is available for download on WordPress.org. Hopefully it fixes your problems.

**Comment by pixolin** [comment]
German Translation 100% (updated Plugin-Readme). Just saying… :)

**Comment by lolux** [comment]
@mpsparrow @ronalfy I've tested 5.4.2 on three GoDaddy Managed WP sites so far, and the plugin is functioning normally. Thanks gents!

**Comment by mpsparrow** [comment]
@lolux: Awesome, glad we were able to fix the issue for you.

@pixolin: Thanks for updating those tranlsations. Many thanks.
