### ISSUE TITLE
Dashboard Layout Errors

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#119]
I don't know if it is just 4.4 or not but the Plugin and Theme Updates box in the dashboard tab of Easy Updates Manager is separated when boxes are only two wide.
![2015-12-08 19_06_24-updates options beta tester wordpress - microsoft edge](https://cloud.githubusercontent.com/assets/6476699/11672504/29fe94e8-9ddf-11e5-83bc-bf0f774ca088.png)

**Comment by mpsparrow** [comment]
Also it appears to add a bigger space in the one column view.
![2015-12-08 19_16_19-updates options beta tester wordpress - microsoft edge](https://cloud.githubusercontent.com/assets/6476699/11673494/4d0dc1a4-9de7-11e5-92b5-9cc694fc2c2f.png)

**Comment by ronalfy** [comment]
Should be fixed with https://github.com/easy-updates-manager/easy-updates-manager/commit/67f2752a2e19a8f8c01168052befc284ec6dc896
