### ISSUE TITLE
Reviews to Convert

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#120]
- [x] https://wordpress.org/support/topic/conflicts-with-wp-engine-installation?replies=9#post- (@ronalfy, did you send him the stuff?)
- [x] https://wordpress.org/support/topic/did-not-prevent-plugin-updating?replies=2#post- (replied and waiting)

I would like to try to get both these reviews to five star reviews.

**Comment by ronalfy** [comment]
Yeah, for the first one I did. Still waiting to hear back.

**Comment by mpsparrow** [comment]
Ok, awesome. I guess we just need to wait for a reply then.

**Comment by mpsparrow** [comment]
I am closing this as the one review is now a 5 star review and the other one is a four star review.
