### ISSUE TITLE
Immediate Switch Changing

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#124]
As said here https://wordpress.org/support/topic/all-updates-switch-could-be-more-elegant?replies=2

Is this worth doing, or is it more trouble then it is worth?

**Comment by ronalfy** [comment]
I think it's worth doing.

**Comment by ronalfy** [comment]
Should be fixed with https://github.com/easy-updates-manager/easy-updates-manager/commit/e37928472d1bbb640a17db85c84bcdb31433403e
