### ISSUE TITLE
Test 5.4.3

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#125]
If @easy-updates-manager/admin can test this out just for sanity sakes, I'll push out an update tomorrow or whenever I hear feedback.

**Comment by mpsparrow** [comment]
I will test it right now...

**Comment by mpsparrow** [comment]
All working for me. The layout error #119  and the new #124 fixes are both working perfectly.

Are you available to release it tomorrow? I need to rest at the moment as I am getting over a sickness.

**Comment by ronalfy** [comment]
Thanks for the help.

Yeah, I can take care of it.

Hope you feel well soon!

**Comment by mpsparrow** [comment]
Thanks. 

Just release it whenever you want. I am still not feeling that great so I am going to be sleeping...

**Comment by mpsparrow** [comment]
I see you released 5.4.3, so I am closing this.

When you have time, If you can merge the dev and trunk branches that would be greatly appreciated.

**Comment by mpsparrow** [comment]
Just so that you know @ronalfy, I just pushed a little typo fix.

**Comment by ronalfy** [comment]
Dev branch has been merged. Thanks. I forgot about that.
