### ISSUE TITLE
WordPress 4.5 RC1

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#127]
One final test should be done to make sure that Easy Updates Manager is fully capable with WordPress 4.5.

**Comment by ronalfy** [comment]
I can test this out this weekend.

**Comment by ronalfy** [comment]
I tested it out on RC-1 just now. Works fine. Good to update readme?

**Comment by ronalfy** [comment]
I went ahead and updated the readme. Tests worked fine.

**Comment by mpsparrow** [comment]
I tested it as well and it works great.
