### ISSUE TITLE
What Ever Happened To Ticket #33932

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#128]
What is happening with [https://core.trac.wordpress.org/ticket/33932](https://core.trac.wordpress.org/ticket/33932)? Did we give up on it?

WordPress 4.6 preparations are starting, so now would be the time to get it in.

**Comment by ronalfy** [comment]
Left a message to john on slack but haven't heard back. I think I need to find a new owner.

**Comment by ronalfy** [comment]
I left a slack to adam silvsrstein. Maybe he can help. I used to work with him.

**Comment by ronalfy** [comment]
Adam looked into it and said submit a patch and ping ocean90 when it's ready.

**Comment by ronalfy** [comment]
May need your help testing it. It has to be perfect.

**Comment by mpsparrow** [comment]
I am more then happy to test it. Is patch 5 the one to test, or are you going to submit another patch?

**Comment by mpsparrow** [comment]
Ocean90 is the release lead I believe, so that makes sense.

**Comment by ronalfy** [comment]
I'll submit another patch. The one I submitted it against is out of date.

**Comment by ronalfy** [comment]
The code will be exactly the same though. So shouldn't take me long.

**Comment by ronalfy** [comment]
I explained the use cases to Adam Silverstein and he absolutely agreed there's a need for this, so I don't think we'll get too much friction.

**Comment by ronalfy** [comment]
@mpsparrow created a new branch that we can switch to easily to test out email notifications.

https://github.com/easy-updates-manager/easy-updates-manager/tree/email-notifications

**Comment by mpsparrow** [comment]
sweet... I shall load that up on my localhost.

**Comment by ronalfy** [comment]
For the dev meeting in case I miss it:

> Can we please consider https://core.trac.wordpress.org/ticket/33932 for the 4.6 milestone? With our plugin and Jetpack, auto-updates are slowly becoming the new normal and users are inundated with emails. New patch has been added. Needs unit tests. Possibly a new core comitter owner who can review the patch and commit.

**Comment by ronalfy** [comment]
Left a slack message for dd32 as he's component maintainer for upgrades. welcher wrote unit tests, so that's all set.

dd32 said to ping him in a week if no further activity has been done on the ticket and it appears he thinks the new filter is a good idea.

Crossing fingers now and trying to be patient.

**Comment by mpsparrow** [comment]
Yes, now we wait....

**Comment by ronalfy** [comment]
Yep, I've been as pro-active as I can at this point.

**Comment by ronalfy** [comment]
Ticket just got updated to the 4.6 milestone.

**Comment by mpsparrow** [comment]
Awesome!

**Comment by mpsparrow** [comment]
In that case I am going to close this ticket and create a new one that will be for adding the new options to disable theme/plugin emails (and also testing the new options).

**Comment by ronalfy** [comment]
👍
