### ISSUE TITLE
Add Setting to Disable Core, Plugin or Theme Emails

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#129]
When WordPress 4.6 is released, which will include [ticket 33932 ](https://core.trac.wordpress.org/ticket/33932), we can add the settings to disable core, plugin or theme emails. 

We could either release a version of Easy Updates Manager on the day WordPress 4.6 is released to include the settings or we can release it early and put a notice under the settings saying that it only works if you have WordPress 4.6. Either way this is on hold until a beta version of WordPress 4.6 comes out that includes our patch.

**Comment by ronalfy** [comment]
Yep, if it gets punted, this issue is no good.

4.6 is my last try. Too much effort has been spent and arguably wasted.

**Comment by ronalfy** [comment]
Assuming ticket is committed and beta is released, we can test and make sure all is well. When the first RC is released, we can put out a new version with a new minimum to prevemt headaches.

**Comment by mpsparrow** [comment]
If they punt it I am going to break something...

As for the releasing on the first RC, sure.

**Comment by ronalfy** [comment]
If you feel like breaking something, just imagine what I'll do :)

**Comment by mpsparrow** [comment]
![computer-smash-other-guys-mark-wahlberg-angry](https://cloud.githubusercontent.com/assets/6476699/14759337/bea97634-08ed-11e6-8c47-c13e53b16b66.gif)

**Comment by ronalfy** [comment]
Updated https://core.trac.wordpress.org/ticket/33932 with my new patch, which is basically Patch 6 with Ryan's unit tests.

Adam didn't like Patch 6 because of all the changes, but after testing today, they are much needed.

**Comment by ronalfy** [comment]
Looks like I'll need to change the code to be `send_debug_notification_email` if the ticket is committed.

**Comment by ronalfy** [comment]
Punted because I was not willing to do any more patches.
