### ISSUE TITLE
Add Help Screen

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#13]
Need to add a help screen to the plugin settings page.  

Dependent on:
- https://github.com/disableupdatespluginproject/Easy-Updates-Manager/issues/10
- https://github.com/disableupdatespluginproject/Easy-Updates-Manager/issues/9
- https://github.com/disableupdatespluginproject/Easy-Updates-Manager/issues/3

**Comment by mpsparrow** [comment]
Awesome!
