### ISSUE TITLE
Resolve PHP notice errors

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#130]
When I was doing my testing today, I came across a myriad of PHP errors that EUM is putting out.

I suggest our next milestone be a bug fix to fix these errors.

**Comment by mpsparrow** [comment]
5.5 bug fixes, 5.6 logs?

**Comment by ronalfy** [comment]
Current version on the repo. I'll paste in some notices tomorrow I'm getting and fix asap.

**Comment by mpsparrow** [comment]
Could https://wordpress.org/support/topic/server-resource-usage?replies=1#post-8341960 have something to do with this?

**Comment by ronalfy** [comment]
Negative. I think all their auto-updates are hitting all at once.

**Comment by mpsparrow** [comment]
You want to reply to it?

**Comment by ronalfy** [comment]
Matthew, this is ready to be tested. I'm comfortable pushing without your input.

Latest changes are in the trunk branch.

Main changes is better reliability in the dashboard widgets, and a spinner to show the progress.

Another change is multiple super admins were being shown, so I fixed that as well.
