### ISSUE TITLE
Test Update Logs

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#131]
@pixolin @mpsparrow would like help testing this feature.

You can find it under this branch: https://github.com/easy-updates-manager/easy-updates-manager/tree/beta_feature

**Comment by ronalfy** [comment]
Bumping this to milestone 6.0. This is a major update.

**Comment by mpsparrow** [comment]
Sweet

**Comment by mpsparrow** [comment]
I will test it in an hour or so.

**Comment by mpsparrow** [comment]
Ok, time to test!

**Comment by mpsparrow** [comment]
One thing, should it not show which version you updated to as well? I think users might get confused about what version number it is showing.

**Comment by mpsparrow** [comment]
That's strange, now it is showing the version it updated to.

**Comment by mpsparrow** [comment]
It would appear that if you automatically update the plugin it shows the version it updated to, as appose to if you manually update the plugin it shows the version it updated from.

**Comment by ronalfy** [comment]
Good catch. I'll do some more testing as well.

**Comment by mpsparrow** [comment]
Same error goes for theme updates.

**Comment by mpsparrow** [comment]
![2016-05-01 23_02_18-bluestacks app player](https://cloud.githubusercontent.com/assets/6476699/14946479/d421200c-0ff0-11e6-88d4-96c8d676ecb7.png)

**Comment by ronalfy** [comment]
Pushed up a fix. It was a caching issue.

![screen shot 2016-05-01 at 10 45 19 pm](https://cloud.githubusercontent.com/assets/636521/14946844/c0f815b4-0fee-11e6-974f-2e4e7b9b94b5.png)

**Comment by ronalfy** [comment]
Noticed a new error in the above screenshot. It looks like automatic updating of core is being saved twice.

**Comment by ronalfy** [comment]
Pushed out a fix for the above.

![screen shot 2016-05-01 at 10 55 54 pm](https://cloud.githubusercontent.com/assets/636521/14946917/fc4f31aa-0fef-11e6-91a5-7bbea3887611.png)

**Comment by ronalfy** [comment]
I'm going to lt this sit on my personal site with all updates automatic to collect more data. Then I can come back to this with fresher eyes. Minor point releases can slowly add in filtering.

**Comment by mpsparrow** [comment]
I just loaded it up on a site that I manage. Things are updated on it daily so it will be a good test to see if it logs it all properly.

**Comment by ronalfy** [comment]
Going to close this down. Let's go per issue from here on out.
