### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#132]
Documentation is in need of an update, especially because of the new update logs.
- [x] New Screenshots
- [x] Update Wiki
- [x] Update Plugin Description
- [x] Update Help Tab
- [x] Video

@ronalfy: Also, one error I have noticed is that in the plugin authors it shows all our names, but then only links to one link. I know it is not possible to link each persons name individually, but maybe to make it look more professional we can just use one name. Like maybe _Easy Updates Manager Team_ or even _MediaRon_. 

![2016-05-01 23_08_46-plugins test site wordpress](https://cloud.githubusercontent.com/assets/6476699/14946556/cfc5557c-0ff1-11e6-86f8-6a1d14988286.png)

You can see what I mean in the image above.

**Comment by mpsparrow** [comment]
As for the screenshots I was thinking of a gif for the log screenshot. Just a quick one showing us enabling logs and then going to the logs tab. Then would just have a plan screenshot for the log.

**Comment by mpsparrow** [comment]
I can do all of this.

**Comment by ronalfy** [comment]
I was planning on creating a video for it.

**Comment by ronalfy** [comment]
Agree about the author section. Just Easy Updates Manager team or something like that.

**Comment by mpsparrow** [comment]
A video sounds good.

**Comment by ronalfy** [comment]
Wiki has been added here: https://github.com/easy-updates-manager/easy-updates-manager/wiki/2.4---Logs

**Comment by ronalfy** [comment]
Video is also completed. https://youtu.be/Z6dPPv8Wttc

**Comment by mpsparrow** [comment]
Wow, you have been busy.

**Comment by mpsparrow** [comment]
I will work on some screenshots for the wiki and plugin in a moment.

**Comment by ronalfy** [comment]
Not sure what to do with the help section or plugin description. Any ideas?

**Comment by mpsparrow** [comment]
I will look into the help section tomorrow. As for the plugin description I was thinking of just adding logs as one of the points under "features include". Zzzzz

**Comment by mpsparrow** [comment]
New screenshots. I just took them from your video.

![2016-05-12 22_16_37-easy updates manager - logs feature - youtube](https://cloud.githubusercontent.com/assets/6476699/15253661/51898fa2-1901-11e6-8124-dcae88b9a6e7.png)
![2016-05-12 22_17_08-easy updates manager - logs feature - youtube](https://cloud.githubusercontent.com/assets/6476699/15253663/519e3182-1901-11e6-840a-b76a776b565c.png)
![2016-05-12 22_17_26-easy updates manager - logs feature - youtube](https://cloud.githubusercontent.com/assets/6476699/15253662/5192f2f4-1901-11e6-9ca1-21bcbcfa6aac.png)

**Comment by ronalfy** [comment]
Awesome. Thanks!

**Comment by ronalfy** [comment]
Okay, got all the screenshots added. Just need your input on the help tab and we're ready to launch this puppy.

**Comment by mpsparrow** [comment]
Help tab is done

**Comment by mpsparrow** [comment]
I merged a few tabs and tweaked some of the text to sound better.

**Comment by mpsparrow** [comment]
Added some images to the logs section in the wiki. That should do it for the wiki.

**Comment by mpsparrow** [comment]
So I think it is safe to say that all the documentation is done.
