### ISSUE TITLE
Make logging themes translatable. 

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#134]
After testing, I'll go in and make the strings translatable.

**Comment by mpsparrow** [comment]
Me and @pixolin are going to be busy translating after this update.

**Comment by ronalfy** [comment]
Should be resolved with: https://github.com/easy-updates-manager/easy-updates-manager/commit/18fc269f1cdb00e2d2b911ea39667dfc53391317
