### ISSUE TITLE
Bug on Automatic Update Failure

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#135]
Does not show the plugin name or version.

![screen shot 2016-05-02 at 10 11 35 am](https://cloud.githubusercontent.com/assets/636521/14958074/62b284ca-104e-11e6-8487-886341fcb666.png)

**Comment by mpsparrow** [comment]
How did you fail an update?

**Comment by ronalfy** [comment]
Expired license

**Comment by mpsparrow** [comment]
smart

**Comment by ronalfy** [comment]
Fixed the above just now.
