### ISSUE TITLE
Change verbage to Manual Updates?

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#137]
See https://wordpress.org/support/topic/does-updates-disabled-mean-no-notifications-as-well?replies=3#post-8374370

**Comment by mpsparrow** [comment]
I see how that can be confusing to some people.

**Comment by mpsparrow** [comment]
The question is what should we change it to?

**Comment by ronalfy** [comment]
Leave it open for now. Need to concentrate on logs.

**Comment by mpsparrow** [comment]
I haven't seen any other complaints about this, so I am thinking _wontfix_ this. Thoughts @ronalfy?

**Comment by ronalfy** [comment]
Go fer it!
