### ISSUE TITLE
6.0.0 Release

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#138]
When you want to pull the trigger? It's probably too late tonight. @ronalfy, you available to do it tomorrow some time?

**Comment by ronalfy** [comment]
I'm not too drunk so I'll do it tonight.

**Comment by ronalfy** [comment]
Hmm, checked out the new diffs and notices that you added a line that said setting to defaults also disables logs. Right now it does not. Should I add that in before launch?

**Comment by ronalfy** [comment]
Actually, I take that back. It does disable the functionality, but does not delete the table.

**Comment by ronalfy** [comment]
Or clear out the table.

**Comment by ronalfy** [comment]
Ok, added some code to drop the table. Ready to launch.

**Comment by ronalfy** [comment]
Launched!

**Comment by mpsparrow** [comment]
Awesome!
