### ISSUE TITLE
Namespacing

### ISSUE THREAD

**Issue by szepeviktor** [easy-updates-manager/easy-updates-manager#14]
Please consider namspacing your classess.
https://github.com/disableupdatespluginproject/Easy-Updates-Manager/issues/4

**Comment by szepeviktor** [comment]
http://greg.harmsboone.org/blog/2014/01/08/how-can-i-use-php-namespaces-in-wordpress-plugins/
http://torquemag.io/using-namespaces-wordpress-development/

**Comment by ronalfy** [comment]
Can't do namespacing until WP drops 5.2 support. Since this is an existing
plugin we are updating, we don't want to drop support and risk a fatal
error.

**Comment by szepeviktor** [comment]
I thought it was 5.3.
https://wordpress.org/about/requirements/
