### ISSUE TITLE
Manual Translation Update Logs

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#143]
See: https://core.trac.wordpress.org/ticket/36872

**Comment by ronalfy** [comment]
@mpsparrow see above for the ticket regarding manual translation logging/updates.

**Comment by mpsparrow** [comment]
Good idea. I agree that that should be added.

**Comment by ronalfy** [comment]
Submitted a patch per above.

**Comment by mpsparrow** [comment]
Nice work.

**Comment by ronalfy** [comment]
Ticket committed!
