### ISSUE TITLE
CSS on List Views Wonky for Checkboxes

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#144]
Checkboxes are green. GREEN!

**Comment by mpsparrow** [comment]
I don't see what you are referring to? Where are they green?

**Comment by ronalfy** [comment]
On the plugins list table and themes lists table.

**Comment by ronalfy** [comment]
When you check a box.

**Comment by mpsparrow** [comment]
Mine are bordered blue...

**Comment by ronalfy** [comment]
Fixed https://github.com/easy-updates-manager/easy-updates-manager/commit/214f218858d408d108e3bd9991999b69b1e389ec
