### ISSUE TITLE
Overriding Default Options

### ISSUE THREAD

**Issue by robneu** [easy-updates-manager/easy-updates-manager#146]
I heard about your plugin via the WP Tavern article and it's pretty sweet! We have something similar to it built into our custom plugin that we install for all WP Site Care customers, but Easy Updates Manager is much more fleshed out and would be easier for our support agents to use.

The one issue I would have with switching over to it is that we need to have different default settings than what your plugin uses. It makes sense to leave everything the way it is in core for most users, but developers and agencies might benefit from being able to globally control what is enabled/disabled by default. I know it would help us.

I had a quick look through the code and I didn't notice filters for this sort of thing. I probably could use Core's [pre_option](https://codex.wordpress.org/Plugin_API/Filter_Reference/pre_option_%28option_name%29) filter in some cases, but I think it could get pretty tedious/weird.

Am I missing how to handle this, or would you be willing to add it in as a feature at some point?

Thanks!

**Comment by ronalfy** [comment]
Would a filter around https://github.com/easy-updates-manager/easy-updates-manager/blob/trunk/includes/MPSUM_Admin_Core.php#L57 work?

**Comment by ronalfy** [comment]
BTW, I'm in love with WP Site Care. My agency is planning on using it bundled with some dev hours.

**Comment by robneu** [comment]
Yup, I think that would cover it for our use case. 👍 

Haha nice! Looking forward to it. 💯

**Comment by ronalfy** [comment]
Cool, adding to the 6.0.5 milestone. Will try to get to it this weekend.

**Comment by robneu** [comment]
Sweet! I could toss together a quick PR if you want.

**Comment by ronalfy** [comment]
Sure. That would be wonderful.

**Comment by ronalfy** [comment]
Merged: https://github.com/easy-updates-manager/easy-updates-manager/commit/93c247c22da2c4c875605f8c9f3139c805513a72

**Comment by ronalfy** [comment]
Just pushed out the update in 6.0.5. https://wordpress.org/plugins/stops-core-theme-and-plugin-updates/changelog/

**Comment by robneu** [comment]
🎉

**Comment by robneu** [comment]
So... coming back around to this... I think I may have misunderstood how the defaults work. Before they're actually saved, it doesn't seem like the defaults actually do anything other than act as a placeholder for the initial settings to be saved.

Is that how they work? If so, I think I might need to figure out another way to handle this. The issue I'm having is we have a large base of sites that need to be pre-set without having to go in and touch each one individually, but can still be overridden by our support techs as-needed.

If that's outside the scope of the plugin, I understand and I can probably figure out another workaround, but it does seem like something that others might run into sometimes.

**Comment by ronalfy** [comment]
Understood. We don't save options unless expicitly saved so we don't accidently override any defaults WordPress has.

What would your idea of a solution be?

**Comment by robneu** [comment]
Well, in my case I can probably just use core's pre_option filter and set some values if they haven't already been saved. At first glance, it looked like all the options were saved to a single value as an array, is that accurate? Are there any best-practices for getting/setting the option using built-in methods?

**Comment by ronalfy** [comment]
We have a static method you can call in main.php called update_options you can use. Context would be core. You can retrieve the options using get_options core and then save your filtered ones.

**Comment by robneu** [comment]
Sweet. I think we should be good on our end.

If you wanted to handle it within the plugin itself, I think the only real option would be to change the "defaults" from presets to true defaults that get used until someone specifically sets an option. As long as they mimic what WP cores defaults are, I don't really see an issue with it. 

It's possible that it could create some unexpected results on some sites I guess, but anyone installing the plugin is probably anticipating some kind of change being made to their updates, so maybe it's fine?

I'll leave that decision up to you guys. Unless I run into some unexpected trouble, I think everything is fine as-is for our use-case.

**Comment by robneu** [comment]
Just in case anyone else stumbles across this in the future, or if you wind up wanting to do something within the plugin at some point, this is more or less how we handled it on our end:

``` php
/**
 * Ensure that all methods in a given array can be called.
 *
 * @since  1.0.0
 * @access public
 * @return bool true if all methods can be called, false otherwise.
 */
function prefix_required_methods_are_callable( $methods ) {
    foreach ( $methods as $class => $method ) {
        if ( ! is_callable( array( $class, $method ) ) ) {
            return false;
        }
    }

    return true;
}

add_filter( 'mpsum_default_options', 'prefix_mpsum_default_options' );
/**
 * Set custom defaults for the Easy Updates Manager options.
 *
 * @since  1.0.0
 * @access public
 * @param  array $defaults The defaults from Easy Updates Manager.
 * @return string
 */
function prefix_mpsum_default_options( $defaults ) {
    $defaults['all_updates'] = 'off';
    $defaults['notification_core_update_emails'] = 'off';
    $defaults['notification_core_update_emails_plugins'] = 'off';
    $defaults['notification_core_update_emails_themes'] = 'off';
    $defaults['notification_core_update_emails_translations'] = 'off';
    $defaults['misc_wp_footer'] = 'off';

    return $defaults;
}

add_action( 'admin_init', 'prefix_mpsum_force_defaults', 20 );
/**
 * Force the custom defaults for the Easy Updates Manager options to be set if
 * no other options have been set.
 *
 * @since  1.0.0
 * @access public
 * @return bool true if the defaults have been forced, false otherwise.
 */
function prefix_mpsum_force_defaults() {
    $safe = prefix_required_methods_are_callable( array(
        'MPSUM_Updates_Manager' => 'get_options',
        'MPSUM_Updates_Manager' => 'update_options',
        'MPSUM_Admin_Core'      => 'get_defaults',
    ) );

    if ( ! $safe ) {
        return false;
    }

    $options = MPSUM_Updates_Manager::get_options( 'core' );

    if ( empty( $options ) ) {
        MPSUM_Updates_Manager::update_options( MPSUM_Admin_Core::get_defaults(), 'core' );
        return true;
    }

    return false;
}

add_action( 'admin_init', 'prefix_mpsum_exclude_wpsitecare', 20 );
/**
 * Force our user to always be excluded from update blocks.
 *
 * @since  1.0.0
 * @access public
 * @return bool
 */
function prefix_mpsum_exclude_wpsitecare() {
    $safe = prefix_required_methods_are_callable( array(
        'MPSUM_Updates_Manager' => 'get_options',
        'MPSUM_Updates_Manager' => 'update_options',
    ) );

    if ( ! $safe ) {
        return false;
    }

    $user = get_user_by( 'login', 'your_user' );
    if ( ! $user instanceof WP_User ) {
        return false;
    }

    $users = (array) MPSUM_Updates_Manager::get_options( 'excluded_users' );

    if ( ! in_array( $user->ID, $users, true ) ) {
        MPSUM_Updates_Manager::update_options( $user->ID, 'excluded_users' );
        return true;
    }

    return false;
}
```

The last part is unrelated to the actual update handling, it's just forcing our default user to be excluded by default.

**Comment by ronalfy** [comment]
Beautiful
