### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by szepeviktor** [easy-updates-manager/easy-updates-manager#15]
Please consider very limited TravisCI testing.
https://github.com/disableupdatespluginproject/Easy-Updates-Manager/issues/4

**Comment by szepeviktor** [comment]
...or users will report the errors instead of Travis.

**Comment by szepeviktor** [comment]
@mpsparrow Are you planning features first then CI later?
That does not look professional.
Please consider working on CI first.

**Comment by szepeviktor** [comment]
Please use https://github.com/xwp/wp-dev-lib for [a lot of things].
*developed by enterprise guys

**Comment by mpsparrow** [comment]
We will consider this but for now I am putting it as a low priority.

**Comment by mpsparrow** [comment]
After a little consideration I have decided that this isn't really needed.
