### ISSUE TITLE
Add Warning to dashboard if a fresh install

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#150]

**Comment by mpsparrow** [comment]
Fresh install of what?

**Comment by ronalfy** [comment]
Fresh install of EUM with no options saved. I have no opinion which way it goes.

**Comment by ronalfy** [comment]
Somebody on the forums today was confused why his plugins weren't updating and he had only the default options (meaning, he/she didn't save anything).

**Comment by mpsparrow** [comment]
Oh, so like a notice saying that you should go and configure Easy Updates Manager?

**Comment by ronalfy** [comment]
Eh, I've thought about this and have decided against it :) - Re-open if you still want to consider this one.
