### ISSUE TITLE
Weird Log Failure

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#151]
![2016-05-24 19_41_15-updates options new connections ministries wordpress](https://cloud.githubusercontent.com/assets/6476699/15523309/821da6c8-21e7-11e6-99de-fb825e27d595.png)

So for some reason the bottom update failed. The website just shut down for a moment (problem on my end). But then when I updated the theme again it successfully updated. The problem is it shows that it was a failure on the logs. The one that worked and the one that didn't were both set as a failure. Any ideas @ronalfy?

**Comment by ronalfy** [comment]
For some reason WordPress cached the failed version, so when the update saw
the versions were the same, it put it as a failure.

**Comment by mpsparrow** [comment]
So is there anything that we can do to fix it?

**Comment by ronalfy** [comment]
Leave it open and I'll try to duplicate it.

**Comment by ronalfy** [comment]
Okay, couldn't duplicate. WordPress doesn't give many options for manual updates, as in if they have failed or not. 

Let's keep this open and see if others have this issue. But as of right now, there's no way to fix it.
