### ISSUE TITLE
Invalid link in FAQ

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#152]
Adding this for reference.

Invalid FAQ link brought up in https://wordpress.org/support/topic/feature-suggestion-send-the-update-notification-emails-to-a-specific-email?replies=5#post-8458277 is fixed in https://github.com/easy-updates-manager/easy-updates-manager/commit/d729501514b807a595687b390bcdd9a5584cb0e0.

**Comment by ronalfy** [comment]
Thanks. Updated on WordPress.org.
