### ISSUE TITLE
Add e-mail option to EUM General Tab

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#153]
Allow users to input e-mails for update notifications.

**Comment by ronalfy** [comment]
@mpsparrow if you get a chance, check out trunk. I placed filters and e-mails in there.

**Comment by mpsparrow** [comment]
Sorry, I have been busy all day. I will look over everything this evening and get back to you.

**Comment by ronalfy** [comment]
Thanks. The only thing I wasn't able to test out 100% was the emails.

**Comment by mpsparrow** [comment]
Tested it all and everything appears to work properly. I really like the new log filters.
