### ISSUE TITLE
Disable and Enable Automatic Updates Not Working Individually

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#158]
https://wordpress.org/support/topic/plugins-link-not-changing?replies=2#post-8575703

I think this may be due to WordPress 4.5.3!?! @ronalfy Can you look into this when you get the chance? 

I am going to do some testing on it right now to try and narrow down the issue.

**Comment by mpsparrow** [comment]
After some testing it is not a conflict problem with WordPress 4.5.3. It appears as if this error started in 6.1.1. Probably due to https://github.com/easy-updates-manager/easy-updates-manager/commit/d81393d8c66a8630935f3a90f901a78928541ebb and https://github.com/easy-updates-manager/easy-updates-manager/commit/07ec37fd3397887f5f08e9063a306790d4b5415a

**Comment by ronalfy** [comment]
Thanks, will take a look.

**Comment by mpsparrow** [comment]
Thanks.

I just reverted those two commits on my localhost install and it appears to be working again which confirms that the problem was made in those commits.

**Comment by ronalfy** [comment]
Can you check trunk now? https://github.com/easy-updates-manager/easy-updates-manager/commit/951b67d907bffd5b23a9a1ee6146702b1846f43f

**Comment by mpsparrow** [comment]
Testing right now... give me a second.

**Comment by mpsparrow** [comment]
Appears to work. Just let me run an update through to make sure that it works.

**Comment by mpsparrow** [comment]
Works!

**Comment by mpsparrow** [comment]
You got the rest? or do you want me to push the update?

**Comment by ronalfy** [comment]
I'll get it out shortly.

**Comment by mpsparrow** [comment]
Ok, thanks!
