### ISSUE TITLE
Help Wanted: Test Manual Translation Logs

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#160]
I've just pushed up a bit of code that enables manual logging of translations.

You can test it by switching the language in Settings->General and then going to Dashboard->Updates and manually updating the languages there.

If all is well, I'll push out an update.

**Comment by mpsparrow** [comment]
It appears to work for me on 4.6 beta1. The only thing is that it doesn't show who the user is that manually updated the translations.

![2016-07-06 12_15_18-](https://cloud.githubusercontent.com/assets/6476699/16625596/5a9d2558-4373-11e6-8416-5fd4a371ebae.png)

**Comment by ronalfy** [comment]
Oh, good catch.
