### ISSUE TITLE
It's that time again...

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#161]
WordPress 4.6 is scheduled to drop on August 16, 2016. RC1 of 4.6 was released today. Time to test Easy Updates Manager against 4.6. If you get any chance to test it @ronalfy that would be great. If you don't, I will be doing a full complete test of Easy Updates Manager with WordPress 4.6 RC1 (when I get around to it in the next week). 

If you do get around to testing it make sure to check over the [4.6 Field Guide](https://make.wordpress.org/core/2016/07/26/wordpress-4-6-field-guide/).

**Comment by mpsparrow** [comment]
I did loads of testing and Easy Updates Manager works fine with WordPress 4.6 RC1.

I am going to leave this thread open until WordPress 4.6 is released just in case any capability issues come up.

**Comment by ronalfy** [comment]
I've had the same success. So far so good.
