### ISSUE TITLE
Screen Options for Dashboard Disable and Logs Pagination

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#162]
Think it would be nice to have a screen options setting to disable the dashboard per user and have an option to increase or decrease the pagination on logs as well.

**Comment by mpsparrow** [comment]
Sounds like a good idea to me. Being able to increase/decrease the pagination on logs will be super helpful.

**Comment by ronalfy** [comment]
Ugh, there's not a way to create custom screen options to disable the dashboard view.

The only way I can think of is to always have a screen options for logs, regardless if logs are enabled or not. Then I can use JS to insert a custom option and save it fix Ajax.

**Comment by ronalfy** [comment]
Yup, this is what I'm going to do :D

**Comment by mpsparrow** [comment]
Let me know when it is ready to test and document.

**Comment by ronalfy** [comment]
Ready for testing on the dev branch.

**Comment by mpsparrow** [comment]
Works well! Why didn't we do this sooner!

**Comment by ronalfy** [comment]
Ha. I'll go ahead and release if you can update the docs?

**Comment by ronalfy** [comment]
Actually I'll wait until the download counter resets and then release. Feel free to update whatever you like.
