### ISSUE TITLE
Fix Radio Buttons for Mobile

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#164]
See screenshot below:

![screen shot 2016-08-17 at 8 33 51 pm](https://cloud.githubusercontent.com/assets/636521/17759047/fc7ff618-64b9-11e6-9ca5-ee54859d98e3.png)

**Comment by mpsparrow** [comment]
Good catch

**Comment by ronalfy** [comment]
Fixed: https://github.com/easy-updates-manager/easy-updates-manager/commit/308a3b53aa705640ff7f786418df93ea7818d805

![screen shot 2016-08-19 at 2 20 27 am](https://cloud.githubusercontent.com/assets/636521/17802104/d2c9f12a-65b3-11e6-8402-a5aa055c686d.png)
