### ISSUE TITLE
Add Screenshot For Screen Options

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#165]
- [x] Update Readme
- [x] Update Assets

**Comment by mpsparrow** [comment]
I already have screenshots for them because of the wiki.

**Comment by mpsparrow** [comment]
![2016-08-17 20_53_06-updates options development wordpress](https://cloud.githubusercontent.com/assets/6476699/17759102/b56fb656-64c2-11e6-8aaa-d1f289855da8.png)
![2016-08-17 20_53_24-updates options development wordpress](https://cloud.githubusercontent.com/assets/6476699/17759103/b67855f8-64c2-11e6-8c6a-b4cf5ad40832.png)

**Comment by ronalfy** [comment]
Cool. I might take a new one if you don't mind.

**Comment by mpsparrow** [comment]
Go ahead

**Comment by ronalfy** [comment]
I'll sit on the release for a week so people don't get update fatigue. Nothing hardcore pressing.

**Comment by mpsparrow** [comment]
Sounds good.
