### ISSUE TITLE
Lots of Log Failures 

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#166]
Looks like a lot of log failures. Are you having the same luck @mpsparrow ?

![screen shot 2016-08-18 at 7 18 46 pm](https://cloud.githubusercontent.com/assets/636521/17794857/ba982e72-6578-11e6-8b30-5baa8f81632c.png)

**Comment by ronalfy** [comment]
![screen shot 2016-08-18 at 7 24 35 pm](https://cloud.githubusercontent.com/assets/636521/17794942/826cf130-6579-11e6-91f7-5b8684b2c320.png)

Different site.

**Comment by ronalfy** [comment]
Looks like WordPress 4.6 changed how the cache and such are updated. We need to have a serious discussion about what this means.

**Comment by ronalfy** [comment]
Ugh! This wasn't there before!

``` php
add_action( 'upgrader_process_complete', 'wp_clean_themes_cache', 9, 0 );
```

**Comment by mpsparrow** [comment]
I just noticed the same thing this afternoon.

**Comment by mpsparrow** [comment]
![2016-08-18 22_14_17-updates options matthews stuff wordpress](https://cloud.githubusercontent.com/assets/6476699/17796758/2e161630-6591-11e6-8ff0-447b24abfb42.png)

**Comment by mpsparrow** [comment]
Seems to be only plugins and themes that are failing out on my websites.

**Comment by ronalfy** [comment]
Should be fixed with this: https://github.com/easy-updates-manager/easy-updates-manager/commit/f838556fc8124d96a74b9449da8b21f63754169d

Should we wait to see real-time results or fix it right away?

**Comment by ronalfy** [comment]
![screen shot 2016-08-19 at 2 03 37 am](https://cloud.githubusercontent.com/assets/636521/17801702/3802e77a-65b1-11e6-8fc3-da692bd8b4b6.png)

**Comment by mpsparrow** [comment]
Let me load it up on a few websites right now and test it. Then maybe we can push it out.

**Comment by mpsparrow** [comment]
Appears to work well! Want to push it out?

**Comment by ronalfy** [comment]
I'm in a meeting until 1pm. I'll push it out after. Thanks for testing.
