### ISSUE TITLE
Releases as Changelogs

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#167]
Should we trim the readme changelogs and just rely on the releases tab for all of them?

I only bring it up because our changelog is getting pretty large.

**Comment by mpsparrow** [comment]
Maybe we should keep the five most recent versions changelogs and then link to the releases page on GitHub for more.

**Comment by mpsparrow** [comment]
https://github.com/easy-updates-manager/easy-updates-manager/commit/55c4c12b20b4d45f76246e5b6c7d7360417bc102 sorts all this out. 

For the future, we should make an effort to put the changelog in the GitHub release so that we have a record of it.
