### ISSUE TITLE
Logs reporting successful plugin update when it actually failed

### ISSUE THREAD

**Issue by jr00ck** [easy-updates-manager/easy-updates-manager#169]
I had a plugin update failing on a bunch of sites recently (CloudFlare 1.3.24 -> 1.3.25). The background updates email log shows this:

> # UPDATE LOG 
> ## CloudFlare 
> 
> Updating plugin: CloudFlare 
> Downloading update from https://downloads.wordpress.org/plugin/cloudflare.1.3.25.zip... 
> Download failed. Not Found 

Checking the websites, the plugin was indeed, not updated and the background update had failed. However, your plugin logged the attempt as successful. I tracked down the issue for you:

Around line 109 of "includes/MPSUM_Logs.php", there is this code:
`$status = is_wp_error( $plugin->result ) ? 0: 1;`

The issue is that when this failure occurs, "$plugin->result" is not a WP error but NULL. So you need to check for that as well. It seems you solved a similar issue for themes already because that code ≈line 135 has this:
`$status = ( is_wp_error( $theme->result ) || empty( $theme->result ) ) ? 0: 1;`

If you do a similar thing on the plugin code (and presumably Core and Translation sections too), that will solve the problem for this particular error.

Note: I noticed when this same updated failed when doing a manual update, your logging actually caught the failure and marked it as such. That section of code was very different than the background updates logging section so that version of code also works.

**Comment by ronalfy** [comment]
Thank you! I'll take a look.

**Comment by ronalfy** [comment]
This is also a bug in WordPress I believe.

https://core.trac.wordpress.org/ticket/38024#comment:8

**Comment by jr00ck** [comment]
Thanks for sharing this! This is a slightly different error (but related, I suppose). I was going to look into this error "[fs_unavailable]” and report to core myself, as I’ve discovered this error before. With this error, their own email logs are mismatched. For example, we get this email on Divi theme updates:

> The following themes were successfully updated: 
> - SUCCESS: Divi Child 
> 
> # UPDATE LOG 
> 
> ## Divi Child 
> 
> Updating theme: Divi Child 
> The theme is at the latest version. 
> Error: [fs_unavailable] Could not access filesystem. 

You can see that it says it was successful up top, but then at the bottom, it actually failed. This error also causes any additional successful updates that happen at the same time to not be logged by your plugin because the "automatic_updates_complete" hook never runs. So if they fix this error in Core, then that will help your plugin in an additional way.

It's possible that whatever fix they implement for this error, could cause the WP Error to not be NULL, I guess, as well. So maybe that would also fix your code? So maybe they are related?

**Comment by ronalfy** [comment]
I think the first is a genuine bug and the latter is the WordPress bug that's been kicking our arses :)

**Comment by ronalfy** [comment]
Automattic people are traveling atm (dd32 is the component maintainer), but Helen put it on a milestone at least so that it will get addressed.

**Comment by jr00ck** [comment]
Perfect! Hopefully this fixes up background updates in Core and you can address anything needed on your end. Let me know if you need anything else from me.

**Comment by tech4him1** [comment]
Any news on this bug yet?

Just as a followup, I am still getting `fs_unavailable` errors on my site, where only one plugin will update at a time.  For example, here is an email from the system:

```
The following plugins were successfully updated:
 * SUCCESS: CloudFlare
 * SUCCESS: Contact Form 7
 * SUCCESS: Jetpack by WordPress.com
 * SUCCESS: Mail On Update
 * SUCCESS: Popups - WordPress Popup

UPDATE LOG
==========

CloudFlare
----------
  Updating plugin: CloudFlare
  Downloading update from https://downloads.wordpress.org/plugin/cloudflare.3.0.6.zip...
  Unpacking the update...
  Installing the latest version...
  Removing the old version of the plugin...
  Plugin updated successfully.

Contact Form 7
--------------
  Updating plugin: Contact Form 7
  The plugin is at the latest version.
  Error: [fs_unavailable] Could not access filesystem.

Jetpack by WordPress.com
------------------------
  Updating plugin: Jetpack by WordPress.com
  The plugin is at the latest version.
  Error: [fs_unavailable] Could not access filesystem.

...
```

The next email will have one item further down the list, like so:

```
The following plugins were successfully updated:
 * SUCCESS: Contact Form 7
 * SUCCESS: Jetpack by WordPress.com
 * SUCCESS: Mail On Update
 * SUCCESS: Popups - WordPress Popup

UPDATE LOG
==========

Contact Form 7
--------------
  Updating plugin: Contact Form 7
  Downloading update from https://downloads.wordpress.org/plugin/contact-form-7.4.5.1.zip...
  Unpacking the update...
  Installing the latest version...
  Removing the old version of the plugin...
  Plugin updated successfully.

Jetpack by WordPress.com
------------------------
  Updating plugin: Jetpack by WordPress.com
  The plugin is at the latest version.
  Error: [fs_unavailable] Could not access filesystem.

...
```

and so on.

**Comment by mpsparrow** [comment]
@tech4him1 

https://core.trac.wordpress.org/ticket/38024 is on the WordPress 4.6.2 milestone and a patch is in the works. We just need to be patient.

**Comment by tech4him1** [comment]
OK, sorry.  I didn't find the patch, and I just wanted to be sure there was progress.  Thank you.

**Comment by ronalfy** [comment]
https://core.trac.wordpress.org/ticket/38024 is fixed and committed. Closing for now.

Tested with two outdated plugins and two outdated themes, and updates and logs behaved as expected.

**Comment by jr00ck** [comment]
Thanks for keeping track of this. I have a busy few weeks of travel and holidays, but I plan to test this again with my specific scenarios around the time WP 4.7 drops, which should include this fix. If there are any issues, I'll followup then. Thanks again1
