### ISSUE TITLE
Keep classes clean

### ISSUE THREAD

**Issue by szepeviktor** [easy-updates-manager/easy-updates-manager#17]
Please try to integrate
https://github.com/disableupdatespluginproject/Easy-Updates-Manager/blob/trunk/updates-manager.php#L194-L197
into the class.

**Comment by ronalfy** [comment]
How would you suggest doing it?  The class needs to be instantiated somehow.

**Comment by szepeviktor** [comment]
Initiate it at real plugin load, and move `add_action( 'plugins_loaded',` into the constructor.

**Comment by szepeviktor** [comment]
``` php
} //end class MPSUM_Updates_Manager

MPSUM_Updates_Manager::get_instance();
```

**Comment by szepeviktor** [comment]
This part could stay
https://github.com/disableupdatespluginproject/Easy-Updates-Manager/blob/trunk/updates-manager.php#L29-L32
code further down could move to a `plugins_loaded()` function.

**Comment by ronalfy** [comment]
Gotcha.

**Comment by szepeviktor** [comment]
Please do consider 80 as a soft limit and **120** as a hard width limit.
Thanks.

**Comment by szepeviktor** [comment]
> 120 is out-of-github.

**Comment by szepeviktor** [comment]
Before that please merge my PR https://github.com/disableupdatespluginproject/Easy-Updates-Manager/pull/19

**Comment by ronalfy** [comment]
For word wrap?  That's not a part of WP coding standards.

**Comment by szepeviktor** [comment]
No, that is not.

**Comment by szepeviktor** [comment]
My tilt mouse will wear out!!

**Comment by szepeviktor** [comment]
Please don't write ugly code.

**Comment by ronalfy** [comment]
I leave Word wrap up to the IDE settings.

**Comment by szepeviktor** [comment]
OK.
I am too strict - at least with myself.

**Comment by szepeviktor** [comment]
Have you seen "your" admin page with https://wordpress.org/plugins/machine-language/ ?

**Comment by ronalfy** [comment]
See https://github.com/easy-updates-manager/easy-updates-manager/commit/06191f2438f664c1dc3531892315645df71425d9
