### ISSUE TITLE
Issue with GoDaddy Hosting - Managed

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#170]
Just got off the phone with GoDaddy and with GoDaddy Managed Hosting, CRON is disabled. This means the normal update process that WordPress uses cannot run.

Not sure what to do at this point, but out of ideas.

**Comment by mpsparrow** [comment]
So CRON is disabled on all GoDaddy hosting? Is there a way to enable CRON in the GoDaddy backend, or are they just screwing all their customers?

_sigh_

**Comment by ronalfy** [comment]
I think they disable server cron and not WP cron. I think it's that
autoupdate bug biting us again.

**Comment by ronalfy** [comment]
Closing. Gardening.
