### ISSUE TITLE
Easy Updates Manager doesn't log updates done through Jetpack Manage

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#171]
When using the Jetpack Manage part of Jetpack, you have the ability to update plugins remotely through wordpress.com. If you use this, it doesn't log the updates through Easy Updates Manager.

Perhaps a FAQ should be created to let users know that Easy Updates Manager doesn't log updates that are done through external software.

**Comment by ronalfy** [comment]
Good catch. I'll investigate if there's a way to log those too, otherwise doc updates.

**Comment by ronalfy** [comment]
Really I see ourselves as a competitor :)

**Comment by mpsparrow** [comment]
They do have automatic updates build into Jetpack Manage. Wouldn't be surprised if they add some more update settings in the future. It's on JETPACK!

**Comment by ronalfy** [comment]
Does this work by adding it to the readme? 

https://github.com/easy-updates-manager/easy-updates-manager/commit/a6b31f6c031a0e9bc7ac0900b2fa01501e78401b

**Comment by mpsparrow** [comment]
I think that is good for now. I don't think it is worth going through the trouble at this time to try and log things like this. Once we allow logging for Jetpack Manage then everyone is going to want us to do it for other 3rd party services. It is probably best if we just stay away from integrating 3rd party services into Easy Updates Manager.
