### ISSUE TITLE
Logs Disable When Settings Saved

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#174]
Still need to do some more testing (will do later this evening), but it would appear as if when you save settings in the General tab it disabled the logs tab and disables logs. 

Easy Updates Manager 6.2.5
WordPress 4.7 RC1

**Comment by ronalfy** [comment]
Good catch!

**Comment by mpsparrow** [comment]
Ok, did some more testing. It appears that it is not an error just with 4.7 RC1. I was able to reproduce the same problem on a fresh install of 4.6.1. The problem is that when you hit the save button on the General tab, no matter if you change a setting or not, it disabled logs.

**Comment by ronalfy** [comment]
Fixed https://github.com/easy-updates-manager/easy-updates-manager/commit/7ab3c75e5fd7bf6fea3ba204ebab71d137a6fcaa

**Comment by mpsparrow** [comment]
Cool! I shall test it right now.

**Comment by mpsparrow** [comment]
Good work! Fixes the problem perfectly.
