### ISSUE TITLE
Remove the "This feature is currently in beta" for logs feature

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#175]
I feel as if we have polished off the logs feature. Perhaps we should remove the following for under the Logs section in the Advanced tab.

> This feature is currently in beta. Use at your own risk. Do not post support requests on WordPress.org. File a GitHub issue instead.

**Comment by ronalfy** [comment]
Sounds good.

**Comment by mpsparrow** [comment]
Perhaps in place of it we should add something explaining what the logs feature does. For example, "This feature enables a Logs tab which will log all updates that occur.".

**Comment by ronalfy** [comment]
Can you try this out and close if appropriate? 

https://github.com/easy-updates-manager/easy-updates-manager/commit/db7792a0124813648647541e47545d3ef2fd09ee

**Comment by mpsparrow** [comment]
Sure
