### ISSUE TITLE
Easy Updates Manager Multisite Testing

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#177]
https://wordpress.org/support/topic/automatic-updates-not-working-on-multisite/

I am hopefully going to get around to testing this along with #176 later today. Although Multisite and me don't get along that well.

**Comment by ronalfy** [comment]
I have a local MS I can test real quick. Sorry was insanely busy yesterday.

**Comment by mpsparrow** [comment]
No problem. If you could test it then and maybe reply to that thread when yo get a chance, that would be greatly appreciated. 

I will do some testing on #176 to see if it is just the website causing the problem or if there is yet another logs problem.

**Comment by ronalfy** [comment]
![screen shot 2017-02-01 at 11 25 14 am](https://cloud.githubusercontent.com/assets/636521/22518155/35ad795c-e871-11e6-83de-160a94db0283.png)

Still working. Must be something else going on, but I have no idea what to try based on the thread.
