### ISSUE TITLE
Migrate function

### ISSUE THREAD

**Issue by szepeviktor** [easy-updates-manager/easy-updates-manager#18]
Please consider it a separate function
https://github.com/disableupdatespluginproject/Easy-Updates-Manager/blob/trunk/updates-manager.php#L81-L148

**Comment by ronalfy** [comment]
Good idea.  Not urgent for launch, but I'll keep it in mind.

**Comment by ronalfy** [comment]
See https://github.com/easy-updates-manager/easy-updates-manager/commit/89f56713f7fd5bafbb1d04026f4e8b798a440281
