### ISSUE TITLE
Test out new Dashboard

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#180]
I need some help testing out the new Dashboard, which was rewritten using React and should be much more stateful. 

To test, download down the react branch.

**Comment by mpsparrow** [comment]
Sure thing, will test it today.

**Comment by ronalfy** [comment]
So far IE8/9 are not working. IE10/11/Edge are.

**Comment by mpsparrow** [comment]
If you are still using IE 8/9 then you are sad.

**Comment by mpsparrow** [comment]
One thing I notice right off the bat is that the dashboard is no longer responsive. Tested on both Windows 10 with Firefox and an Android phone with Chrome and got the same result.

![eum dash test](https://cloud.githubusercontent.com/assets/6476699/23138052/543041b4-f773-11e6-85ac-9e38400a1d9a.png)

**Comment by mpsparrow** [comment]
This is what it use to do. 
![eum dash test 2](https://cloud.githubusercontent.com/assets/6476699/23138167/c0bfa252-f773-11e6-94f8-718fdc60f820.png)

**Comment by mpsparrow** [comment]
What is the point of these checkboxes? I am seeing them in some browsers (Firefox mainly) and not seeing it in others (like Opera).

![eum dash test 3](https://cloud.githubusercontent.com/assets/6476699/23138282/704d91e8-f774-11e6-8c4e-e88230b1ef1f.png)

Update: I only am seeing them in Firefox really, nowhere else are they showing up.

**Comment by ronalfy** [comment]
@mpsparrow responsive styles added back in. I'm not seeing the extra checkbox in FF.

**Comment by mpsparrow** [comment]
The responsiveness works well now.

@ronalfy Are you using Firefox on Mac or Windows? I am seeing on Windows 10 Firefox a clear checkbox like I showed in the screenshot above. Fresh install of WordPress will all the Firefox add-ons disabled. Also seeing on Android Firefox a line in place of the checkbox. Don't know what it could be.

**Comment by mpsparrow** [comment]
Oh, also the "WordPress Notifications" box is to the side. Is it suppose to be like that, or is it suppose to be in the middle column.

![eum dash test 4](https://cloud.githubusercontent.com/assets/6476699/23140750/5458a092-f781-11e6-8a18-74362e10be70.png)

**Comment by ronalfy** [comment]
@mpsparrow That above style bug is fixed now. Which FF are you using? I tried FF 51 in Windows 10 and still do not see the checkbox.

**Comment by mpsparrow** [comment]
@ronalfy 51.0.1

**Comment by mpsparrow** [comment]
It only shows when plugin or theme updates are set to enable, disable, or default.

**Comment by mpsparrow** [comment]
It isn't a huge deal, just a weird thing. Let me try and create another fresh WordPress install just to make extra sure that it isn't on my end.

**Comment by ronalfy** [comment]
I just pushed up a fix. I saw it in 52 Beta.

**Comment by mpsparrow** [comment]
Ok, give me a second to test it.

**Comment by mpsparrow** [comment]
!!!! It worked!

**Comment by mpsparrow** [comment]
Just did a quick check to make sure that all the options are still working well. Everything appears to be working great with this new react dashboard.

**Comment by ronalfy** [comment]
Thanks for all the help!
