### ISSUE TITLE
Ask for ratings option

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#181]
I think a dismissible notice in the dashboard might help us get more ratings.

**Comment by mpsparrow** [comment]
Sure. As long as it isn't too intrusive and easily dismissible, I say we do it.

**Comment by mpsparrow** [comment]
Nice notice! The only thing I am wondering is if a button would be better then a link. Maybe even making the "Sure" option a button would clean it up a little.

**Comment by ronalfy** [comment]
BUTTONS!
