### ISSUE TITLE
dashboard disabling settings it shouldn't

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#183]
See https://wordpress.org/support/topic/dashboard-vs-general/

In the Dashboard tab settings are being disabled when they shouldn't.

**Comment by ronalfy** [comment]
I don't think this is a bug. It's just a confusing experience.

I've asked a colleague who is a UX expert to join this project for evaluation as we re-think the admin interface.

**Comment by mpsparrow** [comment]
Sweet!
