### ISSUE TITLE
"toggle all" button on plugin/theme tables in dashboard

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#185]
https://wordpress.org/support/topic/feature-request-select-individually-toggle-all/

I am leaning towards not doing something like this as you can already do this in the plugin and theme tabs with bulk actions.

**Comment by ronalfy** [comment]
This could be useful for the new interface as I think the tabs might go away.

**Comment by mpsparrow** [comment]
Yeah, when we get to that new interface this is something to consider.

**Comment by ronalfy** [comment]
Since the new admin UI won't have this interface, and people can do this from the plugins tab from now on, I'm marking this as a wontfix.
