### ISSUE TITLE
optimize the readme.txt for new plugin directory

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#186]
The readme.txt could use an update to better optimize it for the new plugin directory on wordpress.org.

**Comment by ronalfy** [comment]
This may be a non-issue with the re-introduction of the tabbed interface into the WordPress plugin directory. 

I recommend keeping this open, however, as they announce the new requirements for the `assets`.

**Comment by mpsparrow** [comment]
Yeah, good idea.
