### ISSUE TITLE
Install Tracking Script

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#189]
With a potential UI overhaul, we actually have very little data on how the users are using the plugin.

I recommend we temporarily hide the rating nag and replace it with a tracking nag instead.

We'll install a tracking script (maybe just Google Analytics) to determine which options are clicked on the most, which tabs are most of least active, and hopefully come up with a better idea of user flow.

From there, we can determine the most used use-cases and come up with user flows on how to achieve this use-case with as minimal effort as possible. 

We currently have a PR sitting, so I can throw a tracking script in on the next bug release fix.

**Comment by mpsparrow** [comment]
Figuring out what each user is doing can really help us better optimize and clean up the Easy Updates Manager settings pages and UI. It will yield far more and better results then if we make a survey nag. Sounds like a good idea to me if it isn't too much trouble. 

Is tracking user data allowed for plugins that are in the WordPress Plugin Repository? I assume as long as we keep the information anonymous it is, although I don't know for sure.

We can push out 6.3.x with this and the pull request bug like you suggested.

**Comment by ronalfy** [comment]
@mpsparrow according to the guidelines, phoning home is allowed as long as it is opt-in.

**Comment by ronalfy** [comment]
@mpsparrow can you check out dev for the tracking functionality? Nothing is being tracked yet, but the UI is there. 

@robneu there's two more options in there if you all are still using this plugin. Filter `mpsum_default_options`.

I'll also need help writing the privacy docs to adhere to the plugin directory guidelines.

**Comment by ronalfy** [comment]
@mpsparrow this is done! Need testing.
