### ISSUE TITLE
Test WordPress 4.8

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#190]
WordPress 4.8 RC2 is out. Let's begin testing. 

I've already tested automatic updates for plugins, themes, and translations and went ahead and updated the tag in the WordPress plugin directory. 

If you have some time, any testing would be much appreciated.

Sidenote: I'm looking into automating this

**Comment by ronalfy** [comment]
![screen shot 2017-06-05 at 5 28 22 pm](https://cloud.githubusercontent.com/assets/636521/26806022/6aea1184-4a14-11e7-98ef-5ab2b79ce637.png)

Forgot to post the log results of my test.

**Comment by mpsparrow** [comment]
Ok, will test it right now.

**Comment by mpsparrow** [comment]
Everything is working great on my end.
