### ISSUE TITLE
Make EUM git friendly

### ISSUE THREAD

**Issue by perandre** [easy-updates-manager/easy-updates-manager#194]
Installing the plugin on a site that is using git for version control (for custom plugins typically), will (by design) not work as intended, as updates will not happen. This is an important usecase for us, as we mix auto updates and git setup for plugins (using inverse .gitignore rules). Any plans on implementing a fix? If not, we can provide a PR tomorrow.

**Comment by ronalfy** [comment]
Definitely a PR. I don't understand the issue.

**Comment by perandre** [comment]
Sure, more obvious when you see it. The fix could live in another plugin, but then again EUM would give the impression of working, while not doing anything. 

We'll hopefully have a PR for master branch tomorrow.

**Comment by ronalfy** [comment]
If you can work the dev branch, that would be much appreciated.

**Comment by perandre** [comment]
Sure! I misses some commits, but that's probably not an issue.

**Comment by ronalfy** [comment]
@perandre I tested this out and it's pretty confusing what it does. I'm not sure we want to add this to the plugin, but I sincerely appreciate the PR.
