### ISSUE TITLE
New EUM Admin Interface

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#196]
Let's discuss what's needed for updating the EUM admin interface.

Background:
Easy Updates Manager used to come with the 4 tabs (General, Plugins, Themes, Advanced). Over time we experimented with a dashboard for quick access to the first three tabs. Logs were added later.

We always considered the Dashboard optional, with a screen option to disable it.

Data Collection:
In anticipation of creating this new admin interface, we started tracking data on keen.io. We noticed that a lot of people were after automatic updates, so we created a new-user modal that will enable that feature.

I expect to remove this modal in the next version as it's been causing issues with some browsers.

New UI:
We're seeking those who can help with the overall design. I'll post the keen.io results here at a later time.

**Comment by paaljoachim** [comment]
The following is a quick wireframe based on one of the earlier wireframes from Shiny Updates.
(NB! I updated the wireframe. )

![update-manager-plugin-wireframe](https://user-images.githubusercontent.com/5323259/31562023-35851a32-b05a-11e7-92e7-0897b1e2a230.jpg)



The thought is this:
Automatic Updates of WordPress, Plugins, Themes, Translations etc.

Below tabs for Plugins, Themes etc.
Click a tab and see for instance all the plugins listed. Bulk select all of them. Or go in and select which to automatically update and which to not automatically update. Manually update when needed.

Click to toggle between "update automatically" and "update manually".

**Comment by mpsparrow** [comment]
I am interested in a simpler one page design. Main thing I am questioning is if it would be possible to fit all the tables and settings comfortably on a page.

**Comment by ronalfy** [comment]
@mpsparrow @paaljoachim 

I'd like to keep the current tabs. I have some ideas for the plugins/themes screen, which I'll do in a later wireframe.

I put together a wireframe for what I think the main tab should look like. I realize Disable updates is one of our least used items, but it kinda makes sense to put it there at the top. The rest of the features are lesser used, but we'll push them more towards the front. 

Of course, Automatic updates is front-and-center. If you click Custom, you'll see options similar to what is on the dashboard. Then you click the plugins/themes tab to configure individually. 

![eum](https://user-images.githubusercontent.com/636521/33036422-ed25f416-cdf3-11e7-8ffd-a7b57c01dba6.png)

**Comment by ronalfy** [comment]
For the plugins and themes screen, I think a button that says [auto][disabled] will work.

**Comment by paaljoachim** [comment]
It looks interesting Ron!

**Comment by mpsparrow** [comment]
I am cool with that design.

**Comment by ronalfy** [comment]
@mpsparrow you can track my progress in the admin-ui branch: https://github.com/easy-updates-manager/easy-updates-manager/tree/admin-ui

I have kept the General tab for now for debugging. When all is well, it will go away.

The hard part is over (the backend, infrastructure, etc). I just need to plow away at the HTML and of course CSS.

Pretty important: I'm using the REST API, so we'll have to update the minimum supported version to 4.7.

**Comment by ronalfy** [comment]
@paaljoachim @mpsparrow here's what I have so far. It's looking good. I'm going to try to see if someone can help with styling. 

![screencapture-eum-options](https://user-images.githubusercontent.com/636521/34756216-e8a05626-f58e-11e7-8900-77125f7e01c3.png)

**Comment by ronalfy** [comment]
Here's the data I promised you @paaljoachim 

According to the screenshot above, the minority of users will NOT see this full UI. Most just want to turn updates on.

![screencapture-keen-io-projects-592e7be03d5e1597cc43a83e-1515559753312](https://user-images.githubusercontent.com/636521/34756270-34d4df80-f58f-11e7-8268-63e850018204.png)

**Comment by ronalfy** [comment]
The new admin UI is done.

Here's the browser tests.

IE8 FUBAR
IE9 Compatible
IE10 Compatible
IE11 Compatible
Edge Compatible
Safari Compatible
Firefox Compatible
iOS Safari Compatible
Android Chrome Compatible

**Comment by mpsparrow** [comment]
Is that Firefox Quantum or the old Firefox @ronalfy?

**Comment by ronalfy** [comment]
@mpsparrow I ran the latest, which I think is Firefox Quantum.

**Comment by ronalfy** [comment]
@roarytubbs you can see some of the thought process above with our data.

**Comment by ronalfy** [comment]
@paaljoachim @roarytubbs @mpsparrow 

Hey y'all, if you have time, can you please try out the new UI and give me your thoughts.

You can download it here: https://github.com/easy-updates-manager/easy-updates-manager/tree/admin-ui

**Comment by paaljoachim** [comment]
Hey Ron @ronalfy 

It looks good but needs some logic adjustments.

1. Words need to confirm a setting when it is on or off. 
Toggle on = The words say enabled
Toggle off = The words say disabled.

It is confusing seeing a greyed out Enable All Updates toggle. It would be natural to have the visual toggle and words mirror/confirm each other. So the greyed out toggle would instead say All updates disabled. The same goes for all options. As I believe people are used to seeing toggles and know they have to click it to make a change.

2. Disable All Updates title. Rename it to All Updates. 
Actually the Master switch is ultimately deactivating the plugin. So this option is not needed. One activates the plugin to be able to control the updates. If one wants to turn off the plugin then one just deactivates it through the installed plugin screen and not the Disable All Updates master switch. 

3. What about placing Logs into the Advanced tab? As I would think that Logs is not that much used. Or Disable/Enable logs. Disabling logs in the Dashboard could also hide the Logs tab.

4. Many of the options under General are also covered in the Dashboard tab. These should be kept in one place. As it can confuse having the same option under two tabs.
Here it would be better to merge the Dashboard and General options into one screen. Keeping it cleaner and easier to understand.

Thats it for now.

**Comment by ronalfy** [comment]
Thanks for the feedback.

For 3, according to our data logs are heavily used.

For 4, the General tab is going away. I left it there for now for testing
purposes.

**Comment by ronalfy** [comment]
Seems like we have a disagreement on point one. The label is attached to the toggle and indicates what’ll happen when clicked. This was based on a recommendation from @morganestes , who is also helping on this project.

@mpsparrow any thoughts?

**Comment by ronalfy** [comment]
For point 2, the disabling updates toggle doesn’t turn off the plugin. If disabled, the plugin prevents any update from occuring.

**Comment by paaljoachim** [comment]
Point 1. Some good reading here: https://ux.stackexchange.com/questions/1318/should-a-toggle-button-show-its-current-state-or-the-state-to-which-it-will-chan/

Point 2. Minor updates is the only automatic update WordPress automatically does. So by turning off the master switch it disables only the minor updates. This can easily be done with the toggle to turn off minor updates though.

**Comment by paaljoachim** [comment]
Here is an example I made with Caldera Forms.

![screen shot 2018-01-14 at 15 06 09](https://user-images.githubusercontent.com/5323259/34916698-85a5ed7c-f93c-11e7-8c2e-9eed7029d7fe.png)

An example:
http://gridlight-design.co.uk/demos/switch.html

I would say the next example is similar to what I am talking about. Visual and with words shows when a toggle is on or off.
https://www.htmllion.com/css3-toggle-switch-button.html

**Comment by ronalfy** [comment]
If I change the toggles to your Caldera example, will that work for you?

**Comment by paaljoachim** [comment]
Yes that should work very well!

**Comment by ronalfy** [comment]
@paaljoachim can you check out https://github.com/easy-updates-manager/easy-updates-manager/tree/admin-ui and get back to me. All toggles have been converted into buttons.

**Comment by paaljoachim** [comment]
It looks a lot cleaner Ron! It clearly says what each option is, and one knows what is selected by the color and the text! Great!

**Comment by paaljoachim** [comment]
Btw text/description outside of the buttons should change depending on option selected. So the user can read the difference in one option in comparison to another.

**Comment by ronalfy** [comment]
Can you give me an example?

**Comment by paaljoachim** [comment]
Here is a test using Caldera Forms and conditional logic:
http://fragmentsofawalk.com/easy-updates-manager-example/

(The above is a dev site for a film club site.)

**Comment by paaljoachim** [comment]
The new buttons look really good.
![screen shot 2018-01-18 at 11 58 35](https://user-images.githubusercontent.com/5323259/35094876-f0f9f084-fc46-11e7-8e8d-1ed1c16733b1.png)

I am now looking at the Plugins and Themes tabs.
Example Theme Update Options as it is right now:
![screen shot 2018-01-18 at 11 41 59](https://user-images.githubusercontent.com/5323259/35094917-15fbad14-fc47-11e7-8962-d73982a431e7.png)

Plugins Update Options:
![screen shot 2018-01-18 at 12 00 13](https://user-images.githubusercontent.com/5323259/35094942-29ff67ec-fc47-11e7-8d6a-8fe02f790c53.png)

Suggestion for change:
An approach that uses the same method as in the new General screen:
(As one decides on going with an approach it is best to stick with it for various screens.)
![easy-updates-manager-plugins-disable-enable](https://user-images.githubusercontent.com/5323259/35095448-c97d9676-fc48-11e7-829f-b6539fbaeedf.jpg)

Plugins and Themes tabs:
- Using buttons that uses the same method as in General screen. Disable/Enable buttons.
- NB! Also notice the left blue border line. It is there beside plugins/themes that are enabled and not there for plugins/themes that are disabled.

---

Btw Going from the new General screen to one of the other tabs and back again shows the General screen blank. This is the error that showed up when clicking Inspect -> Console:

react-dom.production.min.js?fce2:14 Uncaught Error: Minified React error #200; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at E (react-dom.production.min.js?fce2:14)
    at Pg (react-dom.production.min.js?fce2:225)
    at Object.render (react-dom.production.min.js?fce2:227)
    at eval (main.js?0360:23)
    at Object.<anonymous> (admin.js?ver=20171106:953)
    at __webpack_require__ (admin.js?ver=20171106:20)
    at admin.js?ver=20171106:63
    at admin.js?ver=20171106:66

![screen shot 2018-01-18 at 12 04 25](https://user-images.githubusercontent.com/5323259/35095168-cf19a4c2-fc47-11e7-8a32-0c806e3ef18a.png)

**Comment by ronalfy** [comment]
Since the Admin UI is done, let's close this one and talk at https://github.com/easy-updates-manager/easy-updates-manager/issues/202

**Comment by paaljoachim** [comment]
Ok. I copied the last post except the error issue to #202
