### ISSUE TITLE
Manuel upgrade with zip file

### ISSUE THREAD

**Issue by jmoelholt** [easy-updates-manager/easy-updates-manager#197]
Hi
Is it possible to upgrade a plugin or theme manuel with EUM like with the Easy Theme and Plugin Upgrades (https://wordpress.org/plugins/easy-theme-and-plugin-upgrades/)

If not it could be a nice new feature for your else super cool tool.

Best regards
John

**Comment by mpsparrow** [comment]
A feature like that in Easy Updates Manager currently doesn't exist.

What do you think about this @ronalfy?

**Comment by ronalfy** [comment]
This is a huge feature and I think it belongs as a separate plugin.
