### ISSUE TITLE
Ideas for Plugin Placement

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#2]
If you have time, it would be awesome to create an issue with which features you'd like to bring over.  Here are my off-the-cuff ideas.
1.  Create a sub-menu (maybe Updates Manager or Update Options) that works for both Single Site and Multisite.  Single Site can go under the Dashboard menu item (where updates are right now) and Multisite can go under Updates menu item (in Network admin).  Goal is to make this feel 100% like it should be part of WordPress core.
2.  On Multisite, create shortcut actions on the themes/plugins pages.
3.  For our sub-menu, create a native WordPress tabbed interface with different sections.  Maybe Core Updates, Plugins, and Themes.  Plugins/Themes could be a custom list table (where my plugin can come in), and I envision Core Updates to work very much like the existing plugin you have.

An alternate to a sub-menu, as you have mentioned, is a parent menu item.  I haven't given this much thought, but if you can weigh in with your ideas, that would be awesome.

Nice-to-have:
1.  Recognize plugin/theme header (that we define a standard for) that when present, we automatically ignore updates for this plugin/theme.
2.  Hide constant that can be defined in wp-config.  This will hide our plugin and its options from being changed and/or de-activated.  This will allow an admin user to install the plugin, set up options, then when done, "hide" the plugin so that changes are pseudo set it stone.  This is kinda what Advanced Custom Fields does.

Multisite compatibility:
MS compatibility isn't hard to achieve, it's just a matter of keeping track of admin urls, options, and capabilities.  I'll help in any regard to make sure this plugin has 100% MS compatibility.

**Comment by mpsparrow** [comment]
I like your ideas. 
- We need to make it 100% Multisite capable.
- We need to keep the main features of Disable Updates Manager alive as to not lose people. We should still have some smaller settings like disable auto updates. Also, I was thinking that it would be awesome if we could add a feature to disable major and minor core updates individually.
- I have always liked the ideas of tabs as appose to submenus or just one great long page with all the settings. The tabs can be divided into a Cover page, Core Options, Theme Options, Plugin Options, and Other Options (we can rename these). We can then use your plugin to add in the tables to disable theme and plugin updates individually. Also, maybe on the Cover page we could add one big setting that disables or enables all the settings.
- Also, any new name suggestions?

**Comment by ronalfy** [comment]
How about Updates Manager?  I'm not that creative with names :)

It doesn't look like it's taken:  https://plugins.trac.wordpress.org/browser/updates-manager

I'll try to begin porting stuff over this week.

**Comment by mpsparrow** [comment]
I think Updates Manager is good. Are we going to submit this as a new plugin or as an update to Disable Updates Manager?

**Comment by ronalfy** [comment]
That is an insanely good question.  I'd hate to get rid of the download count and good karma that your existing plugin has.

My gut reaction is keep the slug, just rename the plugin.  Unfortunately we can't get plugins@wordpress.org to do it because they say it's fairly impossible and recommend just starting a new repo if the plugin is different enough.

If we keep the same plugin, we'll need some type of migration script that will run when an older version is detected.  I don't foresee this being a huge deal, but it means we need to get our options in order for the update.

**Comment by mpsparrow** [comment]
So I guess we can just updates the current repo then. It can be version 5.0 of Easy Updates Manager.

Anyway, we should start crunching on the coding. Do you have a good enough idea of what the plugin is going to be like so that we can start coding?

BTW, you may not know this but I am not really that great at coding. I coded this plugin with a little help from a few contributors and a lot of time (a few months to be exact). So in other words you may be doing a fair amount of coding.

**Comment by ronalfy** [comment]
Sorry, been really busy with a deadline.

Let me take a closer look at the plugin and see what makes sense. I'll try
to have a better answer Saturday and hopefully some code to go with it.

**Comment by mpsparrow** [comment]
That's ok, there is no deadline for this plugin. In fact, it is better if we take our time as to not make mistakes.

**Comment by szepeviktor** [comment]
It isn't taken: https://wordpress.org/plugins/updates-manager

**Comment by szepeviktor** [comment]
Could you list all these in https://github.com/disableupdatespluginproject/Easy-Updates-Manager/issues/6?

**Comment by szepeviktor** [comment]
Closed by https://github.com/disableupdatespluginproject/Easy-Updates-Manager/issues/6

**Comment by mpsparrow** [comment]
If you think of any other ideas use https://github.com/disableupdatespluginproject/Easy-Updates-Manager/issues/6.
