### ISSUE TITLE
Release blocker

### ISSUE THREAD

**Issue by szepeviktor** [easy-updates-manager/easy-updates-manager#20]
Please rename repo:
Easy-Updates-Manager -> easy-updates-manager

All WP plugins are lowercase.

**Comment by ronalfy** [comment]
Not sure what you mean?  Why would the GitHub repo name have anything to do with it?

**Comment by szepeviktor** [comment]
A developer - like me - could `git clone` the repo and ends up with an Upper-Case-Named folder.

**Comment by ronalfy** [comment]
Ah, good point.  I'll like @mpsparrow chime in.

**Comment by ronalfy** [comment]
It's pretty easy to do, but it's his repo :D

**Comment by mpsparrow** [comment]
Will do.

**Comment by mpsparrow** [comment]
Done
