### ISSUE TITLE
NEW version: Error going from General tab to another tab and then back again.

### ISSUE THREAD

**Issue by paaljoachim** [easy-updates-manager/easy-updates-manager#204]
(I am transferring this issue from EUM interface isssue.)

Btw Going from the new General screen to one of the other tabs and back again shows the General screen blank. This is the error that showed up when clicking Inspect -> Console:

react-dom.production.min.js?fce2:14 Uncaught Error: Minified React error #200; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at E (react-dom.production.min.js?fce2:14)
    at Pg (react-dom.production.min.js?fce2:225)
    at Object.render (react-dom.production.min.js?fce2:227)
    at eval (main.js?0360:23)
    at Object.<anonymous> (admin.js?ver=20171106:953)
    at __webpack_require__ (admin.js?ver=20171106:20)
    at admin.js?ver=20171106:63
    at admin.js?ver=20171106:66

![screen shot 2018-01-18 at 12 04 25](https://user-images.githubusercontent.com/5323259/35095168-cf19a4c2-fc47-11e7-8a32-0c806e3ef18a.png)

**Comment by mpsparrow** [comment]
I am not able to reproduce this. Is it still happening in the most recent version on the dev branch?

**Comment by paaljoachim** [comment]
From what I see this has now been fixed.
