### ISSUE TITLE
NEW Version: Looking at conditionals

### ISSUE THREAD

**Issue by paaljoachim** [easy-updates-manager/easy-updates-manager#205]
I am looking at the conditionals. (Btw instead of the word disable-enable I changed the language here to on and off.)

http://fragmentsofawalk.com/easy-updates-manager-example/

1. Example.
Click to turn Master Switch to OFF turns OFF everything else.

2. Example.
 Click to turn off Automatic Updates.

**Comment by paaljoachim** [comment]
Hmm I was sure I had posted the following but I can not find it right now...

Btw
http://fragmentsofawalk.com/easy-updates-manager-example/

Example 1 with turning of the master switch.

Example 2.
Default - On - Off- Custom.
On = Turns all themes and plugins etc to on.
Off = Turns all themes and plugins etc to off
Custom = If off and one turns on theme/plugin etc then it goes to custom. If on and one turns theme/plugin etc to off then this switch goes to custom.

I will see if there are additional thoughts I need to add here. As we need to talk more about the logic conditionals.

**Comment by ronalfy** [comment]
I'd prefer to avoid the conditionals because that takes us back to the
Dashboard land, which people found confusing. I'm fine with the admin UI
the way it currently works.

**Comment by paaljoachim** [comment]
Ok.
