### ISSUE TITLE
Plugin name

### ISSUE THREAD

**Issue by szepeviktor** [easy-updates-manager/easy-updates-manager#21]
Is _Updates Manager_ OK?
https://github.com/disableupdatespluginproject/Easy-Updates-Manager/blob/trunk/updates-manager.php#L3

**Comment by szepeviktor** [comment]
Description: _Manage WordPress Updates - Works with Multisite_

Maybe it can tell the user about _what_ it controls: core, themes, plugins etc.

**Comment by szepeviktor** [comment]
~~Are translation updates planned to be disabled?~~

**Comment by szepeviktor** [comment]
_Update Options_ sounds like it should be under _Settings_.
Consider _Update Control_ or similar.

**Comment by ronalfy** [comment]
I think it's going to be Easy Updates Manager.  Not sure what the menu title should be, but I'm open to suggestions.

I like the current placement.  It's where the other update settings are located in WordPress.

**Comment by szepeviktor** [comment]
I don't suggest to move it.

**Comment by ronalfy** [comment]
I'll give it a go.  The goal is to make this thing look / behave like core as much as possible.

**Comment by mpsparrow** [comment]
I think we should call the plugin Easy Updates Manager but we can change the settings title to make it seem more core-like.
