### ISSUE TITLE
Impossible to allow only translations updates

### ISSUE THREAD

**Issue by brocheafoin** [easy-updates-manager/easy-updates-manager#213]
Hi there,

As I [have already said](https://wordpress.org/support/topic/update-only-languages/), this is a fantastic plugin. I think I have found an issue with it, though. What we're trying to do is to only allow translations updates but when I apply what looks like the correct settings for this, the translation updates that were previously visible disappear from the Updates page. Here are steps to reproduce:

1. Download and install [WordPress 4.9.4 in French](https://fr.wordpress.org/wordpress-4.9.4-fr_FR.zip) (or another language, but this version and language worked for my demo purposes)
2. Add the `define( 'AUTOMATIC_UPDATER_DISABLED', true );` line to wp-config.php as soon as possible to prevent auto-updating from downloading missing translations.
3. Install and activate Easy Updates Manager.
4. Visit the Updates page in the admin. You should see updates available for Core, Akismet, the default themes and translations.
5. Configure Easy Updates Manager as follows:  _Disable Core Updates_, _Disable Plugin Updates_ and _Disable Theme Updates_
6. Head back to the Updates page and you will see that no updates at all are available. The available translations have disappeared.
7. Change the Easy Updates Manager configuration to _Enable Plugin Updates_ and go back to the Updates page. Lo and behold, new translations available!

[Here is an album with the relevant screenshots](https://imgur.com/a/kxZnEtN).

As far as I can tell, the problem comes from the [last_checked_now()](https://github.com/easy-updates-manager/easy-updates-manager/blob/e71acac34e0d6f2857456bcc3f02c143c8835e8b/includes/MPSUM_Disable_Updates_Plugins.php#L64) methods which completely override the information contained in the updates transient. Since translations are not first class citizens in the WordPress update system, but children of either core, plugins or themes updates, they get axed by this method.

**Comment by ronalfy** [comment]
We found a fix. Hopefully it should be in the next release.

**Comment by ronalfy** [comment]
7.0.3 was just released with your fix.

**Comment by brocheafoin** [comment]
Hi! Sorry for the late reply, I was on vacation. Unfortunately, 7.0.3 only switches the problem around. Now, when only translation updates are allowed, plugins and themes updates show even if they should not. See screenshots below.

I'd be happy to take a crack at it and submit a pull request, but it seems this repo is not in sync with the actual development of the plugin.

Settings:
<img width="759" alt="settings" src="https://user-images.githubusercontent.com/784119/43092985-d5a99a0a-8e7c-11e8-858e-7d1cf0e9adf4.png">

Available updates:
![available_updates](https://user-images.githubusercontent.com/784119/43092984-d58fd868-8e7c-11e8-84ea-a602cefe7015.png)

**Comment by ronalfy** [comment]
@brocheafoin,

Go ahead and submit a PR and I'll cherry-pick the commits into the next release.

@DavidAnderson684 can we update the git repo here with an appropriate tag upon every release?

**Comment by ronalfy** [comment]
@brocheafoin I have solved this and will hopefully go into the next release. It was quite involved.

**Comment by brocheafoin** [comment]
> It was quite involved.

Yes, it felt to me like it would be. Thanks for the hard work!
