### ISSUE TITLE
When disabling major releases, WP should not send out notification mails for such

### ISSUE THREAD

**Issue by amenk** [easy-updates-manager/easy-updates-manager#214]
Use case: I have a site which should "just work" in kind of LTS mode, i.e. security updates should be done automatically and I want to have a notification for those.
But any major updates should not happen.

So far so goodl

![image](https://user-images.githubusercontent.com/1087128/53297630-65880500-3821-11e9-9f81-0052eaa54787.png)

So I am currently on 4.9.9

But I am still getting a daily mail telling me:

> WordPress 5.1 is available. Please update!

I feel this mail should be suppressed, when major updates are disabled.

**Comment by amenk** [comment]
Mail seems to be generated here: `wp-admin/includes/class-wp-automatic-updater.php:610`

There is a filter:

		if ( 'manual' !== $type && ! apply_filters( 'auto_core_update_send_email', true, $type, $core_update, $result ) )
			return;

But it works only if the `$type` is not manual ...

Maybe hook into this one?

		$email = apply_filters( 'auto_core_update_email', $email, $type, $core_update, $result );

**Comment by amenk** [comment]
Also manual core updates (via wp-admin) should just be deactivated in such cases ... like it is with the plugins, when updates are disabled.

**Comment by DavidAnderson684** [comment]
@amenk

Notification settings are in the 'General' tab:

![image](https://user-images.githubusercontent.com/1962275/53329686-836a6e00-38e4-11e9-9ffa-11db217c5d3a.png)

**Comment by DavidAnderson684** [comment]
Disabling core updates entirely is also a separate option from disabling automatic core updates:

![image](https://user-images.githubusercontent.com/1962275/53329898-1dcab180-38e5-11e9-8c76-f0933dc0f584.png)

![image](https://user-images.githubusercontent.com/1962275/53329923-333fdb80-38e5-11e9-87be-c00f1a1fe136.png)

**Comment by amenk** [comment]
Thank you @DavidAnderson684 , but I do not see the option "Update notification mails". I am on WP 4.9 and Plugin version 8.0.3

![image](https://user-images.githubusercontent.com/1087128/53685249-6f75a080-3d18-11e9-8f04-9b9c52a186b3.png)

I think if it would be there, it's exactly the option I need

* I want get mails about successfully done automatic core updates (minor updates)
* But I do not want to be informed about the available major updates I am not doing

**Comment by DavidAnderson684** [comment]
I was looking at the Premium version - if you're not seeing it, that must have meant it's not in the free version (sorry for not checking that earlier).

**Comment by amenk** [comment]
Phew, that really should make it into the free version ... -_-

**Comment by amenk** [comment]
Fun fact:

"Email Notification of Available Updates" is supposed to NOT be in the free version, but it IS in the paid version... but I still receive those updates

**Comment by DavidAnderson684** [comment]
Hi Alexander,

To be clear: what's not in the free version is code that supplies controls to modify WP's default behaviour.

David
