### ISSUE TITLE
Plugins and Themes lists

### ISSUE THREAD

**Issue by szepeviktor** [easy-updates-manager/easy-updates-manager#24]
Please don't paginate those lists.

**Comment by szepeviktor** [comment]
...like WP core.

**Comment by ronalfy** [comment]
They should be paginated.  It's unrealistic to have an infinitely long table.  I can bump the args to maybe 100, but I'm not going unlimited.

**Comment by szepeviktor** [comment]
See how WP core does it: https://github.com/WordPress/WordPress/blob/master/wp-admin/plugins.php#L364

**Comment by szepeviktor** [comment]
You've just commited to be "core-alike".

**Comment by ronalfy** [comment]
Ack.  Then so be it.  999 it is.

**Comment by ronalfy** [comment]
See https://github.com/easy-updates-manager/easy-updates-manager/commit/0cfa9e2b0927e23d715d3051c39a573f57c7599f
