### ISSUE TITLE
All Updates "enabled"?

### ISSUE THREAD

**Issue by szepeviktor** [easy-updates-manager/easy-updates-manager#25]
_If enabled, this will override all settings._

I've enabled _All Updates_ and disabled all other options: updates were still disabled.

**Comment by ronalfy** [comment]
That's what it should do.

**Comment by szepeviktor** [comment]
"If enabled, this will override all settings." === "If enabled, all updates will be enabled." ?

**Comment by ronalfy** [comment]
Maybe I should rephrase...  If updates are disabled, this will override all settings.

**Comment by szepeviktor** [comment]
I am totally confused now.
Which radio button does the _override all_?

All Updates: Enabled OR Disabled ?

**Comment by ronalfy** [comment]
Updates disabled.  Updates enabled is just default WP behavior.

**Comment by szepeviktor** [comment]
Oh!
"If enabled, this will override all settings." should be "When disabled, updates will be completely disabled."

**Comment by ronalfy** [comment]
Okay, now I'm confused.  I'm away from my developer mac, but I'll check the settings and make the change where it makes sense.

**Comment by ronalfy** [comment]
Oh, nm.  I see.  Yes, "If updates are disabled, this will override all settings"

**Comment by szepeviktor** [comment]
"If **this option** is disabled" - to be specific.

**Comment by ronalfy** [comment]
See https://github.com/easy-updates-manager/easy-updates-manager/commit/b13c97df170b83eed68622a9a1201efdc1e15fc6
