### ISSUE TITLE
WP-like settings page

### ISSUE THREAD

**Issue by szepeviktor** [easy-updates-manager/easy-updates-manager#26]
In `options-reading.php` you find:

``` html
<tr>
<th scope="row">For each article in a feed, show </th>
<td><fieldset><legend class="screen-reader-text"><span>For each article in a feed, show </span></legend>
<p><label><input name="rss_use_excerpt" type="radio" value="0"  checked='checked'   /> Full text</label><br />
<label><input name="rss_use_excerpt" type="radio" value="1"  /> Summary</label></p>
</fieldset></td>
</tr>
```

Please follow WP-like input-in-label tag structure.

**Comment by szepeviktor** [comment]
Test tool: https://wordpress.org/plugins/machine-language/

**Comment by szepeviktor** [comment]
Please consider writing a function that generates this block of HTML.

**Comment by ronalfy** [comment]
It's a good idea and I wish we could use the settings API in multisite, but let's consider this for a future release.

**Comment by szepeviktor** [comment]
Are you telling me that Settings API does not work on multisite installs?
Or is it misunderstanding also :smile:

**Comment by ronalfy** [comment]
No, Settings API, per my understanding, does not.

**Comment by ronalfy** [comment]
Like in the network admin area.

**Comment by ronalfy** [comment]
I'm going to push this to a later release. Not important for the time-being.

**Comment by ronalfy** [comment]
I'm going to go ahead and close this. It's a nice-to-have, but noone else has brought this up as an issue.

Thanks for the original report though.
