### ISSUE TITLE
Check again button works a bit

### ISSUE THREAD

**Issue by szepeviktor** [easy-updates-manager/easy-updates-manager#27]
Does one:

```
POST
https://api.wordpress.org/core/version-check/1.7/
?version=4.1.1
&php=5.6.5-1
&locale=en_US
&mysql=5.5.5
&local_package=
&blogs=1
&users=3
&multisite_enabled=0
```

**Comment by ronalfy** [comment]
Looking at the code of wp_version_check, there's no way to exit this function if $force_check is true.

**Comment by szepeviktor** [comment]
`empty( $_GET['force-check'] )` see:
https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/mu-disable-updates/disable-updates.php#L72

**Comment by szepeviktor** [comment]
Don't remove actions when _Check again_ is clicked.

**Comment by mpsparrow** [comment]
@Ronalfy: are you going to fix this? It is marked as wontfix but at the same time you assigned it for a feature release.

**Comment by ronalfy** [comment]
No, go ahead and close it. This is normal behavior and I don't want to get
hacky fixing it.
