### ISSUE TITLE
Admin page setting names

### ISSUE THREAD

**Issue by szepeviktor** [easy-updates-manager/easy-updates-manager#28]
Plugin Updates could be _All_ Plugin Updates, and _Automatic_ Plugin Updates.
Themes as well.

**Comment by ronalfy** [comment]
See https://github.com/easy-updates-manager/easy-updates-manager/commit/8950ee8ea9b0ed419d9a71857a5b4734d3ac54fb

**Comment by szepeviktor** [comment]
@ronalfy You are doing it fast.

**Comment by mpsparrow** [comment]
He is fast at typing. I can barley keep out with him.
