### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#29]
Please check out the Wiki and add/edit what you think is appropriate.

I'll be adding a developer page that will go over the Advanced tab in more detail, have some filter rules, and go over the wp-config constant that will hide the plugin.

**Comment by mpsparrow** [comment]
Sounds good. I just made a quick wiki but it would be good if we went into more details.

**Comment by mpsparrow** [comment]
I think that for now this is done. We have the basics of the plugin and how to use it.
