### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by szepeviktor** [easy-updates-manager/easy-updates-manager#3]
I would gladly do a video tutorial.
https://www.youtube.com/watch?v=8o3g85SeDQ8
https://www.youtube.com/watch?v=1ymdwgSHHYs

**Comment by mpsparrow** [comment]
Yes, we should defiantly have a professional looking video tutorial for this plugin.

**Comment by mpsparrow** [comment]
@szepeviktor: Would you like to do this when we are done the plugin?

**Comment by szepeviktor** [comment]
Yes.

**Comment by szepeviktor** [comment]
Please privide my a scipt to read. Or at least a list to talk about.

**Comment by mpsparrow** [comment]
Yah, we can talk about it more once we are done the plugin. For now, we need to code the plugin.

I am going to assign you for this.

**Comment by ronalfy** [comment]
Videos needed
- [x] General Informational Video
- [x] General Options
- [x] Plugin Options
- [x] Theme Options
- [x] Advanced Options

**Comment by mpsparrow** [comment]
We need to release the plugin. I keep getting e-mails from people about errors in Disable Updates Manager. If we don't release it in the next week then we could lose lots of downloads.

**Comment by ronalfy** [comment]
Agreed.  The plugin could use some more testing, such as a raw install of the old plugin, configure, overwrite files, test options migration.  Note any errors or bad UX.

I've been sick for the past 5 days and finally got my voice back, so I'll try to do some videos tonight.

**Comment by mpsparrow** [comment]
Ok great! I can do some more testing on my localhost install to check for any errors.

Great that you got your voice back!

**Comment by mpsparrow** [comment]
Also just added you as a committer to the plugin. You can push the update of the plugin when were ready.

I have to go right now but I can do the testing this evening (hopefully).

**Comment by ronalfy** [comment]
Heya, here's a link to the video playlist:  https://www.youtube.com/playlist?list=PL7YF6bIhLLz0HzndENZZAdoh2nJBefTeA

And here's the channel where I'm posting all the videos.

https://www.youtube.com/channel/UCGGX_ELs6WyvgJCtUC58uLw

**Comment by ronalfy** [comment]
They're not perfect, but I think they work.  Closing for now.

**Comment by mpsparrow** [comment]
Nice! They give a nice overview of the plugin. I also like it that you made a channel to put them all in as appose to just putting them on a personal channel.
