### ISSUE TITLE
Add Beta Tester Options

### ISSUE THREAD

**Issue by szepeviktor** [easy-updates-manager/easy-updates-manager#30]
It is Beta or Nightly?
https://wordpress.org/plugins/wordpress-beta-tester/

**Comment by ronalfy** [comment]
http://codex.wordpress.org/Configuring_Automatic_Background_Updates#Core_Updates_via_Filter

To specifically enable development (nightly) updates, use the following:

``` php
add_filter( 'allow_dev_auto_core_updates', '__return_true' );
```

**Comment by szepeviktor** [comment]
Everyone doing WP dev is used to wordpress-beta-tester settings.
https://plugins.trac.wordpress.org/browser/wordpress-beta-tester/trunk/wp-beta-tester.php#L106

**Comment by szepeviktor** [comment]
I'm just telling you this is the _standard_ WP dev plugin.

**Comment by ronalfy** [comment]
Let's set this for a future release.  Add an option to select Nightly, Point, or None.

**Comment by ronalfy** [comment]
Let's close this issue. The beta plugin does a good job, and looking at the support requests, I don't think this is something we should take on.

@mpsarrow, close if you agree.
