### ISSUE TITLE
Use variables

### ISSUE THREAD

**Issue by szepeviktor** [easy-updates-manager/easy-updates-manager#31]
https://github.com/disableupdatespluginproject/Easy-Updates-Manager/blob/8f050163d421c97233621f72452ff0e94133f593/includes/MPSUM_Disable_Updates.php#L48-L108
Please take the advantage of variables.

**Comment by szepeviktor** [comment]
``` php
 add_filter( 'allow_dev_auto_core_updates', $variable, 50 );
```

**Comment by ronalfy** [comment]
I'd prefer to use the core WP functions.

**Comment by szepeviktor** [comment]
Of course!
Please reduce `add_filter()` usage from 2 to 1.

**Comment by szepeviktor** [comment]
Something like

``` php
    //Enable Core Minor Updates
if ( isset( $core_options[ 'automatic_minor_updates' ] ) {
    switch ( $core_options[ 'automatic_minor_updates' ] ) {
        case 'on':
            $allow_minor_auto_core_updates = '__return_true';
            break;
        //case 'off':
        default:
            $allow_minor_auto_core_updates = '__return_false';
            break;
    }
    add_filter( 'allow_minor_auto_core_updates', $allow_minor_auto_core_updates, 50 );
}
```

**Comment by ronalfy** [comment]
I see what you mean.  I think it's a preference thing vs if/else and switch statements.  If you want to do a pull request, go for it :D

**Comment by szepeviktor** [comment]
Depending on the default state.

**Comment by ronalfy** [comment]
You also have to keep in mind that some of these plugin settings aren't set yet, so there's not really a default.  I only do the filter if an option is explicitly set.

**Comment by szepeviktor** [comment]
You can also write an abstract function

``` php
function set_it( $option_name, $filter_name, $priority = 50 ) {
}
```

**Comment by szepeviktor** [comment]
Is there a case for unset radios??

**Comment by szepeviktor** [comment]
Here it is: http://keszul.tk/tamasi/ (radios can be unset)

**Comment by ronalfy** [comment]
No, there are radio boxes, but those are checked or unchecked based on defaults.  

https://github.com/disableupdatespluginproject/Easy-Updates-Manager/blob/trunk/includes/MPSUM_Admin_Core.php#L12-L28

**Comment by ronalfy** [comment]
But until a user goes to the General tab and saves the options, they don't exist in the options table yet.

I do this purposely so that the plugin doesn't make default assumptions on how WordPress should be updated.

**Comment by szepeviktor** [comment]
Yes. I've meant radio boxes everywhere above.

**Comment by szepeviktor** [comment]
``` php
set_from_radio( 'automatic_minor_updates', 'allow_minor_auto_core_updates' );
```

**Comment by ronalfy** [comment]
A switch statement should be able to work, but there is no "default" option.

**Comment by szepeviktor** [comment]
Abstraction is good practice.

**Comment by ronalfy** [comment]
I agree.  I did it with the saving/retrieving of options.  Not a huge fan of abstracting out filters though.  Makes it a pain for others to see what's going on.

**Comment by szepeviktor** [comment]
Name your functions properly + DocBlock.

**Comment by ronalfy** [comment]
I'm a fan of abstraction when it makes sense.  In this case it doesn't.
