### ISSUE TITLE
off: Option debugging

### ISSUE THREAD

**Issue by szepeviktor** [easy-updates-manager/easy-updates-manager#32]
https://github.com/szepeviktor/option-inspector
Go to Settings / Options click on a serialized value.

**Comment by mpsparrow** [comment]
@Ronalfy, what do you think about this?

**Comment by mpsparrow** [comment]
I don't see the point in this.

**Comment by szepeviktor** [comment]
If you have to know tha value of a serialized option:
just click on it in Settings / Options
That simple.

**Comment by szepeviktor** [comment]
Maybe you are in that situation when you develop a plugin.

**Comment by mpsparrow** [comment]
But that has nothing to do with Easy Updates Manager.

**Comment by szepeviktor** [comment]
That's what "off" stands for.

This is today's new plugin: https://wordpress.org/plugins/plugin-installer-speedup/
Helps speeding up plugin installation.

**Comment by szepeviktor** [comment]
...maybe while developing Easy Updates Manager you'd take a look at a serialized option.

**Comment by mpsparrow** [comment]
Your plugins look very nice, but can you please stop trying to promote them here.

**Comment by szepeviktor** [comment]
OK-OK.
