### ISSUE TITLE
Add translation files

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#33]
Add translation to Easy Updates Manager.

**Comment by ronalfy** [comment]
Thanks, I'll do this as soon as most of the strings are finalized.

**Comment by mpsparrow** [comment]
Ok thanks.

**Comment by ronalfy** [comment]
See https://github.com/easy-updates-manager/easy-updates-manager/commit/cf849ed5b3d8598ffa7bfeaf819141ff4b58f9dd

**Comment by mpsparrow** [comment]
Great
