### ISSUE TITLE
Add option to toggle uninstall.php

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#34]
Add an option in the Advanced section to toggle on/off the uninstall.php.

**Comment by mpsparrow** [comment]
What do you think about this @easy-updates-manager/owners?

**Comment by ronalfy** [comment]
Schweeet!

**Comment by mpsparrow** [comment]
I will add it to the 5.1 milestone.

**Comment by mpsparrow** [comment]
I am bumping this to a future release for now as the 5.3 milestone is full with the Dashboard tab.

**Comment by ronalfy** [comment]
When you have time, can you explain the importance of this issue and a use-case?

**Comment by mpsparrow** [comment]
There isn't to much importance to this. It is a nice to have feature.

The reason for adding this is if you are deleting the plugin but still want to keep all the settings for if you reinstall it. I am questioning it though seeing as no one has complained about this.

**Comment by ronalfy** [comment]
Okay, hoping there is a filter that hopes with this. I'll investigate and get back. If no filter, then there simply isn't away with WordPress unless we get a patch approved, and with something like this, I doubt it very much.

**Comment by ronalfy** [comment]
in `wp-admin-includes-plugins.php` there is a function called `is_uninstallable_plugin`. This area makes the most sense for a filter, but there simply isn't one.

I can hook into get_option and remove the uninstallable plugins.

In `wp-includes/option.php`, there is a filter: `pre_option_$option`.

So to get uninstall to work, I need to hook into that filter: `get_option('uninstall_plugins')`.

I hope that's not technical, but that's the only feasible approach. What say you?

**Comment by ronalfy** [comment]
I'd place the above in the Advanced Tab. Don't want non-developers using this.

**Comment by mpsparrow** [comment]
Its up to you. If you think that it will work well and securely then I say we have a go at it.

> I'd place the above in the Advanced Tab. Don't want non-developers using this. 

Agreed, the Advanced Tab is the place for this to go.

**Comment by ronalfy** [comment]
Cool. I actually might be able to work on this today. Roary and I are about
to head to a coffee shop.

**Comment by mpsparrow** [comment]
Awesome!

**Comment by ronalfy** [comment]
Sorry Matthew, the more I think about this, the less I want to do it. This would be better I think as a separate plugin. I'd like to keep the focus on managing updates, not managing plugins.

**Comment by mpsparrow** [comment]
Ok. I understand.
