### ISSUE TITLE
Tranlsation Updates Setting not working in 4.2 beta 1

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#36]
Translation updates are still showing even if setting is turned to disabled. This is in 4.2 beta 1.

**Comment by ronalfy** [comment]
Maybe this is a separate issue.  The option for translation updates covers automatic updates, and doesn't do anything to prevent them from showing.

**Comment by ronalfy** [comment]
Solved with https://github.com/easy-updates-manager/easy-updates-manager/commit/27e11f6a6179aca5616748f5f1910c384e7823bc

The option you used was the one for automatic translations, which does not disable translation updates.  It merely enables/disables automatic translation updates.

I added in another option which allows you to disable the translation notifications.

**Comment by mpsparrow** [comment]
perfect
