### ISSUE TITLE
Different fake values

### ISSUE THREAD

**Issue by szepeviktor** [easy-updates-manager/easy-updates-manager#38]
Please be notified that users reported slow page load on WP.org support.

Here: https://github.com/easy-updates-manager/easy-updates-manager/blob/trunk/includes/MPSUM_Disable_Updates_All.php#L139
3 different fake values are needed:
See: https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/mu-disable-updates/disable-updates.php#L172-L216

**Comment by ronalfy** [comment]
What is the issue?  I'm returning the exact same thing.

**Comment by mpsparrow** [comment]
This is not a problem is Easy Updates Manager. It was a problem in Disable Updates Manager but seeing as @easy-updates-manager/owners re-wrote the plugin (resulting is Easy Updates Manager), these values are no longer a problem with the admin page load speed. In fact, I thing the Easy Updates Manager settings page loads as fast if not faster then most admin pages.
