### ISSUE TITLE
Migrating Options Question

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#39]
In the update, when the plugin migrates the old options, it deletes the old options in the migration process.

Should we leave this so there is a downgrade path, or just go with it?

The problem with leaving it is it'll just clutter up the options table.  And if someone's options are wiped out, they can easily just re-configure the plugin.

Thoughts?

**Comment by mpsparrow** [comment]
I say we just leave it as is. If this appears to be a problem then we can release a minor update to fix it.
