### ISSUE TITLE
Code quality

### ISSUE THREAD

**Issue by szepeviktor** [easy-updates-manager/easy-updates-manager#4]
Good morning!

How about adding some thoughts for your plugin?
- separate languages: PHP, HTML, SQL, CSS, JS
- separate functionality: admin, frontend
- doc blocks
- max line length, soft=80, hard=120
- basic CI test
- performance
- security (nonce)
- [WordPress Coding Standards](http://codex.wordpress.org/WordPress_Coding_Standards)
- cheating: https://github.com/Yoast/wordpress-seo
- 1 PHP file in plugin dir

**Comment by szepeviktor** [comment]
[WordPress Coding Standards](http://codex.wordpress.org/WordPress_Coding_Standards)

**Comment by ronalfy** [comment]
Thanks.  I haven't had a chance to work on this, but I do plan on using WP coding standards, doc blocks, etc.

I'm probably also going to utilize an auto loader.

**Comment by szepeviktor** [comment]
Do you work on it in private?

**Comment by szepeviktor** [comment]
@ronalfy What is your taget audience? Will it a be a popular (noone should see the source) or enterprise (code audit could yield positive results) plugin?

**Comment by mpsparrow** [comment]
Now that the coding is done, we don't really need this either.
