### ISSUE TITLE
Release Version 5.0

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#40]
Now all that is left is to release version 5.0. Do you (@Ronalfy) want to do it,  or would you like me to do it?

**Comment by mpsparrow** [comment]
Ok, just made a minor fix. Now it is ready (in less you have anything to commit).

**Comment by ronalfy** [comment]
If it is okay, I'd like to do this.  I'd like to do one sanity test at home on a prod box and then pull the trigger.  I can do this tonight and then I'll subscribe to the .org forums to get any support requests.

**Comment by mpsparrow** [comment]
Sounds great.

Yes, we should add that it is tested to 4.2 beta1.

**Comment by mpsparrow** [comment]
Sounds good.

**Comment by mpsparrow** [comment]
For support we can both watch the WordPress.org forum and answer stuff there. If there are any thing that need to be fixed from one of the WordPress.org topics then we should add it to GitHub with a link to the main topic.

**Comment by ronalfy** [comment]
Roger that.  Agree.

**Comment by mpsparrow** [comment]
Ok, looking forward to when it is released!

**Comment by mpsparrow** [comment]
Also, don't forget to add in the screenshots when you release it.

**Comment by ronalfy** [comment]
It is alive!!!!  https://wordpress.org/plugins/stops-core-theme-and-plugin-updates/

**Comment by mpsparrow** [comment]
Awesome!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by mpsparrow** [comment]
Already has 500+ downloads today.

**Comment by ronalfy** [comment]
We broke 800 and zero support queries so far :)

**Comment by mpsparrow** [comment]
Still no support topics.
