### ISSUE TITLE
"Skip" feature idea

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#41]
https://wordpress.org/support/topic/skip-feature-idea?replies=2

I thought this was a pretty good idea. We could add the feature for the plugins and themes straight in the plugin and theme tables. There could just be a simple drop down that you could click on to select which version you would like to disable (it would also disable all the versions below it). We could also add feature for the core updates.

The only thing that I am questioning it if there is a way to disable a specific plugin, theme, or core version (i.e. disable only WordPress 4.0).

@easy-updates-manager/team What do you think?

**Comment by ronalfy** [comment]
This is a good idea. It's a pretty involved feature though.

**Comment by mpsparrow** [comment]
Yah, that's why I added it for a future release.

**Comment by ronalfy** [comment]
There are absolutely no hooks in update-core.php. So sad. Closing as it isn't currently possible unless we do it using our interface, which I don't think would be a good UX.

Regretfully closing this issue, as I like the idea.
