### ISSUE TITLE
Resolve current topics on the WordPress support forum

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#42]
- [x] https://wordpress.org/support/topic/updates-have-not-been-stopped?replies=2
- [x] https://wordpress.org/support/topic/disable-all-didnt-work?replies=2
- [x] https://wordpress.org/support/topic/theme-updated-despite-being-disabled?replies=7
- [x] https://wordpress.org/support/topic/does-not-seem-to-be-working-3?replies=8

**Comment by ronalfy** [comment]
Thanks! A lot of these I can't duplicate and suspect it might be hosts
doing these updates. I'll keep testing though.

**Comment by mpsparrow** [comment]
Any update on how this is going? Need help?

**Comment by ronalfy** [comment]
I've set up tests on most of these scenarios. Unable to duplicate at all.

**Comment by mpsparrow** [comment]
I am wondering whether some of these were just a one time occurrence.

**Comment by mpsparrow** [comment]
Are you going to make a workaround video? https://wordpress.org/support/topic/does-not-seem-to-be-working-3?replies=10

**Comment by mpsparrow** [comment]
Is this the type of workaround for that? http://birdhouse.org/blog/2013/11/02/force-wordpress-auto-update/

**Comment by ronalfy** [comment]
Yes, I do plan to. I just haven't gotten to it yet.

The technique above doesn't work 100% of the time.  The best way is to modify /wp-includes/version.php' and bump the version down. Then use a cron plugin (I like the Sucuri plugin for this) to re-trigger the update crons.

I used this to test the WordPress core auto-updates, and it has the added bonus of also triggering the auto-updates for plugins/themes.

**Comment by mpsparrow** [comment]
Ok sounds good. Are you planning just to make a video tutorial for it and post it on the Easy Updates Manager YouTube channel?

**Comment by ronalfy** [comment]
Yeah, and I'll respond to the thread as well. Just a matter of finding the time to do it.

**Comment by mpsparrow** [comment]
Ok sounds good! (don't feel rushed)

**Comment by mpsparrow** [comment]
For now I am going to mark https://wordpress.org/support/topic/theme-updated-despite-being-disabled?replies=7 as resolved because they appear to not be having the problem.

 As for
 https://wordpress.org/support/topic/does-not-seem-to-be-working-3?replies=8
 I think I am going to mark this as resolved because you posted the answer.

Any objections @easy-updates-manager/team?

**Comment by ronalfy** [comment]
None here.

**Comment by mpsparrow** [comment]
Ok then. I am closing this issue seeing as the person in the one support topic left is not replying.
