### ISSUE TITLE
Change text on WP "Updates" view

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#43]
https://wordpress.org/support/topic/change-text-on-updates?replies=2

**Comment by mpsparrow** [comment]
I am questioning whether or not this is worth it. Some people would like it to show that Easy Updates Manager is disabling the updates but at the same time other people may not want this to show because they are hiding it from a client or something. @easy-updates-manager/team what do you think?

**Comment by ronalfy** [comment]
I'd rather leave it default.
