### ISSUE TITLE
Test Capability with 4.3 (RC and Betas)

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#46]
@easy-updates-manager/owners: We should all make a fresh install and test Easy Updates Manager with each new beta and RC.

**Comment by mpsparrow** [comment]
Should also be tested with MU.

**Comment by mpsparrow** [comment]
Just tested on a fresh single 4.3 beta 1 site and it all appears to be working.

**Comment by ronalfy** [comment]
Thanks, I'll be able to test this out this weekend.

I don't anticipate any issues. The plugin, for a major point release, is insanely stable.

**Comment by mpsparrow** [comment]
> I don't anticipate any issues.

Yes, neither do I. Nothing to do with the updates system have been changed in 4.3. But nevertheless we should still test it to ensure that the plugin is safe and secure.

I am planning on doing some more testing this weekend and/or some early next week.

**Comment by mpsparrow** [comment]
As far as I have tested everything is working well with 4.3 RC1. I am planning on doing a little more multisite testing but I think we are safe for the update to WordPress 4.3, that is if you haven't found anything.

**Comment by mpsparrow** [comment]
I have done tons of testing on this lately and have found no errors with 4.3 RC1. I am closing this.
