### ISSUE TITLE
WordPress 4.3 Field Notes (Lots of Changes for Plugin Developers!)

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#47]
We should look over these changes to make sure that none affect Easy Updates Manager.

https://make.wordpress.org/plugins/2015/08/08/wordpress-4-3-field-notes-lots-of-changes-for-plugin-developers/

**Comment by ronalfy** [comment]
Multisite and single-site considerations have been applied.
