### ISSUE TITLE
5.1 Release

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#48]
We haven't released an update in a while. With WordPress 4.3 being released on August 18, 2015, I think this is a perfect time to do a 5.1 release of Easy Updates Manager.

Current issues for 5.1 milestone:
- [x] https://github.com/easy-updates-manager/easy-updates-manager/issues/47
- [x] https://github.com/easy-updates-manager/easy-updates-manager/issues/34 ?
- [x] https://github.com/easy-updates-manager/easy-updates-manager/issues/30 ?
- [x] https://github.com/easy-updates-manager/easy-updates-manager/issues/46 (in less @ronalfy found any other problems)

Let me know what you think.

**Comment by ronalfy** [comment]
Looks like the menus changed in multisite, so I had to move it to the Dashboard area like in Single Site.

This means we either need a WP version check, or just bump the minimum requirement to 4.3.

**Comment by ronalfy** [comment]
Let's skip #30 for this release. It's a bit involved.

**Comment by ronalfy** [comment]
Actually 4.3 will be a required min req for this release. Too many changes.

**Comment by ronalfy** [comment]
Let's defer #34 to milestone 5.2.

**Comment by ronalfy** [comment]
Issue #47 is now resolved.

**Comment by ronalfy** [comment]
I'm ready to release this when you are.

**Comment by mpsparrow** [comment]
Awesome. Do you think we should release it now or when 4.3 is released?

**Comment by mpsparrow** [comment]
Also the FAQ in the readme.txt could use an update.

**Comment by ronalfy** [comment]
I think ASAP as this is related to the multisite issues: https://wordpress.org/support/topic/crap-breaks-backend#post-

I'll check out the FAQ tomorrow, but feel free to edit. Maybe after the 3rd RC we can push this out?

**Comment by mpsparrow** [comment]
Sure sounds good. I can have a look at the FAQ Thursday.

Yes, lets plan to release it then.

**Comment by ronalfy** [comment]
Sounds amazing.

If you're worried about the min version, I wouldn't be. As an updates manager, it's kind of our prerogative to be with core as much as possible.

**Comment by mpsparrow** [comment]
Yes, I am not that worried about the minimum version. If people want a version that works with 4.2 then they can download a past version. The only thing is I don't want to update the version before 4.3 comes out and then have people using 4.2 and 5.1. Then we will get endless support topics about how it is not working.

Nice video by the way ;)

**Comment by mpsparrow** [comment]
I updated the FAQ a little. I think it is good for now.

**Comment by ronalfy** [comment]
Awesome. I'll push this out this evening. Thanks!

**Comment by mpsparrow** [comment]
Great!

**Comment by ronalfy** [comment]
Released.

**Comment by mpsparrow** [comment]
Awesome!!!

**Comment by mpsparrow** [comment]
Just noticed that Easy Updates Manager is now running on 30,000+ installs!

**Comment by ronalfy** [comment]
Wowzers
