### ISSUE TITLE
Miscellous thoughts

### ISSUE THREAD

**Issue by szepeviktor** [easy-updates-manager/easy-updates-manager#5]
- Hooks with code examples (e.g. list of must-be-disabled plugins)
- [version without UI](https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/mu-disable-updates/disable-updates.php)
- Prevent also HTTP requests
- Translation updates
- Popular non-WP.org plugin updates e.g. WPML

**Comment by szepeviktor** [comment]
How to code tabs on admin:
http://media.mediatemple.netdna-cdn.com/wp-content/uploads/2011/10/Sample-Theme_tabbed.zip

**Comment by szepeviktor** [comment]
Example for auto updates: https://github.com/chipbennett/update-control

**Comment by szepeviktor** [comment]
Translation updates.

**Comment by szepeviktor** [comment]
Popular non-WP.org plugin updates.
E.g. WPML

**Comment by mpsparrow** [comment]
Now that the coding is done, we don't really need this either.
