### ISSUE TITLE
Minor Release After 4.3 is Out

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#50]
As you may have noticed, our downloads have went down because of our minimum version requirement of 4.3.

I think once 4.3 is out, we'll see a significant increase in downloads.

I anticipate a flood of support requests, just like we saw with 4.2.

Let's keep track of issues and assign them to milestone 5.1.1.

**Comment by mpsparrow** [comment]
> I think once 4.3 is out

It is not out yet but as far as I can tell it will be out later this afternoon.

> Let's keep track of issues and assign them to milestone 5.1.1.

Will do

**Comment by mpsparrow** [comment]
4.3 is out now!

**Comment by ronalfy** [comment]
Let the games begin.

**Comment by mpsparrow** [comment]
Are downloads are skyrocketing. We have gotten 50 download in the last 5 minutes.

**Comment by ronalfy** [comment]
Wowzers, a definite jump.

**Comment by mpsparrow** [comment]
1700 already today and no reported problems

**Comment by ronalfy** [comment]
Very awesome.

**Comment by mpsparrow** [comment]
Ok, above the 2,000 download mark today and still no reported problems. If we don't get any by this weekend then I think we can close this.

**Comment by ronalfy** [comment]
Yes. 2000 is pretty epic if you ask me. And no support? Wowzers.

**Comment by mpsparrow** [comment]
Ok, it has been just over a week since 5.1.0 was released. 5000+ downloads and no real support issues. The only thing is what is up with this https://wordpress.org/support/topic/plugin-not-updating-5?replies=7 ?
