### ISSUE TITLE
Test German Translation

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#51]

**Comment by mpsparrow** [comment]
Just tested this now. It appears to work great on both multisite and single site. The only thing is that the Allow Updates and Disallow Updates words in the plugin and theme tables dropdown selectors don't appear to be translated on both multisite and single site installs. 
![screenshot 2015-08-19 14 04 06](https://cloud.githubusercontent.com/assets/6476699/9364630/65e7fa32-467b-11e5-9eb7-6cdc7b8806c8.png)

**Comment by mpsparrow** [comment]
It is also not translating the Allow and Disallow automatic updates.
![screenshot 2015-08-23 16 30 37](https://cloud.githubusercontent.com/assets/6476699/9430081/3aa02be6-49b5-11e5-86ef-27886f510c1b.png)

Besides that everything else appears to be translating.

**Comment by mpsparrow** [comment]
Actually there is one other thing that was actually missed in the translating, the plugin description. @pixolin: Is it possible for you to translated the plugin description for us?
![screenshot 2015-08-23 16 42 59](https://cloud.githubusercontent.com/assets/6476699/9430107/0cd5eb6e-49b6-11e5-8bc9-f78b17784be0.png)

**Comment by mpsparrow** [comment]
Ok, merged https://github.com/easy-updates-manager/easy-updates-manager/pull/56 so now the plugin description is translated. So now it is just the dropdown not translating properly.

**Comment by pixolin** [comment]
Ups … What did I miss?

**Comment by ronalfy** [comment]
@pixolin I don't think you missed anything.

@mpsparrow: I forgot to update the text domain strings here: https://github.com/easy-updates-manager/easy-updates-manager/blob/trunk/includes/MPSUM_Plugins_List_Table.php#L248

**Comment by ronalfy** [comment]
I won't have time during the work day, but I can do this after 1800 CST.

@mpsparrow if you want to change those to the right slug, go for it and I'll push out an update later.

**Comment by pixolin** [comment]
I was about to mention that. :)

You either missed the text domain or used a wrong name for the text domain in /includes/MPSUM_Plugins_List_Table.php and /includes/MPSUM_Themes_List_Table.php, too. 

I need to bring my kid to her sports now, but can fix that later and update the language files, of you want?
It's nothing big anyway, as it seems.

**Comment by ronalfy** [comment]
Let's go ahead and close this and I'll include a new issue. Thanks for the help @pixolin

**Comment by pixolin** [comment]
Uhm … OK … but do you want me to patch this? I'm about to finish a pull request for at least /includes/MPSUM_Plugins_List_Table.php :)

(After all it's my fault because I started with that translation mess.) ;)

**Comment by ronalfy** [comment]
@pixolin Sure, if you like. It's both the plugins and themes list table. I'll update it when I get home if I don't hear back.

**Comment by ronalfy** [comment]
@mpsparrow I had to revert the pull request as it caused some PHP errors.

Can you check that the dropdowns are working now?

**Comment by ronalfy** [comment]
Closing this, all seems to be well. Re-open if there are any more issues.
