### ISSUE TITLE
Update Screenshots to Reflect 4.3 Admin

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#52]

**Comment by mpsparrow** [comment]
The previous screenshots were also a little big. We should try to keep it below a 700px width if possible.

**Comment by mpsparrow** [comment]
I can take care of this if you would like.

**Comment by ronalfy** [comment]
Sure, go for it! Thank you!

**Comment by mpsparrow** [comment]
Just added the new screenshots to 'Easy Updates Manager New Screenshots' folder in Dropbox. Have a look and tell me what you think.

**Comment by mpsparrow** [comment]
Ok, https://github.com/easy-updates-manager/easy-updates-manager/commit/9d0ec1cae27f8dcd905f23cb40d843f6636befcf includes the updated screenshot description. So screenshots and information are done.

**Comment by ronalfy** [comment]
Looks good. Thanks for handling this.

**Comment by mpsparrow** [comment]
No problem.
