### ISSUE TITLE
Dashboard Tab View Idea

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#53]
I think it would be cool to add a "Dashboard" like screen when people go to our plugin.

I envision it to have an at-a-glance view of what settings are enabled/disabled.

I also think it would be cool to have some quick options that will mimic what a user would select.

Examples:
- Free sailing mode - Enable all updates and automatic updates
- Disable all WordPress updates (core, plugins, themes)
- Enable / Disable all WordPress Automatic Updates (core only)
- Enable / Disable all WordPress Plugin Updates (plugins only)
- Enable / Disable all WordPress Theme Updates (themes only)

If you like this idea, let's put this on the 5.2 milestone and move 5.2 to 5.3, etc.

**Comment by mpsparrow** [comment]
Haha, I was think of this exact same thing a hour ago. A dashboard tab would defiantly help people to not get confused on what is disabled/enables. It would be nice if the dashboard simplified that.

I think we can add this to the 5.2 milestone and then bump the other stuff to 5.3 like you suggested.

**Comment by ronalfy** [comment]
I have a designer friend who may be willing to help with this. Punting to 5.3. Goal is the new Jetpack screen.

**Comment by mpsparrow** [comment]
Sounds great! What is his name? I would be more then willing to add him to the Easy Updates Manager GitHub admin.

**Comment by ronalfy** [comment]
He wants a tour first, but he's a very talented guy. I work with him on the daily. We'd almost have to have a separate milestone for that. Maybe just a different branch. I'll create one based on master if he shows more interest.

**Comment by mpsparrow** [comment]
Sound awesome! We could either make the Dashboard tab the only thing in 5.3 or just make a 5.4 that only includes it. Either way I think we should make a 5.2.1 milestone that includes https://github.com/easy-updates-manager/easy-updates-manager/issues/69#issuecomment-141593519 and whatever else comes up before then.

**Comment by ronalfy** [comment]
Let's see if we can get some .org testers and launch Sunday. Hopefully translations up-to-date by then.

**Comment by mpsparrow** [comment]
Sounds good. You want to notify them or would you like me to?

**Comment by ronalfy** [comment]
I got it :D Thanks though.

**Comment by mpsparrow** [comment]
awesome, thanks

**Comment by ronalfy** [comment]
We put a lot of work into this plugin, so I don't have any ethical boundaries having a major version bump for a few features.

**Comment by mpsparrow** [comment]
Ok, for now I am moving the dashboard tab to 5.3 and the skip feature to 5.4.

**Comment by ronalfy** [comment]
Related https://github.com/easy-updates-manager/easy-updates-manager/issues/76

need wireframes first.
