### ISSUE TITLE
change main.php to easy-updates-manager.php

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#54]
https://wordpress.org/support/topic/directory-name-1?replies=2

**Comment by ronalfy** [comment]
If we do this, we break things.

**Comment by mpsparrow** [comment]
Ok then.

**Comment by ronalfy** [comment]
Sorry, didn't intend to sound blunt. I actually tried to change this for 5.0, but it caused plugin deactivation since I changed the main plugin file.

Not really anything we can do.
