### ISSUE TITLE
disabling/enabling plugin or theme automatic updates shows wrong notice 

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#55]
When you are enabling or disabling plugin or theme automatic updates individually it shows "The selected plugin updates have been disabled.". Should it not say something like "The selected plugins automatic updates have been disabled"?

![screenshot 2015-08-23 15 38 51](https://cloud.githubusercontent.com/assets/6476699/9429875/20dc81c6-49ad-11e5-96fc-284cb1701e60.png)

**Comment by mpsparrow** [comment]
I added it to 5.2 but if you think otherwise then feel free to change it.

**Comment by ronalfy** [comment]
Let's get this out for 5.1.1.

**Comment by ronalfy** [comment]
Resolved: https://github.com/easy-updates-manager/easy-updates-manager/commit/58af844873d7419b716a56cdfcc919b6b939ad25

**Comment by mpsparrow** [comment]
Thanks!
