### ISSUE TITLE
Release 5.1.1

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#59]
Let's push this out today or tomorrow.
- [x] Update readme with screenshot information
- [x] Commit new screenshots into SVN assets folder
- [x] Ensure new screenshots are mime-type image/png or image/jpg
- [x] Add translator props to readme

Anything I missed?

**Comment by mpsparrow** [comment]
No, I think that is all.

**Comment by mpsparrow** [comment]
Ok, everything appears to be working except for the plugin description is not translating and the new notice in https://github.com/easy-updates-manager/easy-updates-manager/issues/55 in not translated into German either.

Besides that the screenshots are completely done and in the assets folder. Also https://github.com/easy-updates-manager/easy-updates-manager/issues/55 notice changes are working.

**Comment by ronalfy** [comment]
I left my laptop at work, so I'll do the deploy tomorrow.

**Comment by mpsparrow** [comment]
Ok, sounds great!

**Comment by ronalfy** [comment]
It is released.

**Comment by mpsparrow** [comment]
Awesome!

**Comment by mpsparrow** [comment]
and a new download record!!! 2,174 and counting

**Comment by ronalfy** [comment]
Geez
