### ISSUE TITLE
"Approved" Goals for First Version

### ISSUE THREAD

**Issue by szepeviktor** [easy-updates-manager/easy-updates-manager#6]
- [x] Make MU-enabled
- [x] Organize settings in tabs, metaboxes, submenus, and/or parent menu
- [x] Recognize plugin/theme header
- [x] Hide constant defined in wp-config
- [x] Keep important features of Disable Updates Manager (disable plugins and themes individually, disable core).
- [x] Change name.
- [x] Make a professional video tutorial.
- [x] [Code quality](https://github.com/disableupdatespluginproject/Easy-Updates-Manager/issues/4).
- [x] Make a logo or icon of some sort for the WordPress cover image (772px x 250px) and plugin icon (128px x 128px).

**Comment by szepeviktor** [comment]
@mpsparrow Are you willing to list all agreed goals?

**Comment by mpsparrow** [comment]
They are basically all in the Plugin Placement issue. https://github.com/disableupdatespluginproject/Easy-Updates-Manager/issues/2

**Comment by szepeviktor** [comment]
I was thinking about using this GitHub feature: to-do list.
Maybe it is easier to read.

**Comment by mpsparrow** [comment]
It would defiantly make it easier to have it all in one list. If you are willing to do it then that would be awesome.

**Comment by szepeviktor** [comment]
I let you edit it.

**Comment by mpsparrow** [comment]
Ok, I will work on the list.

**Comment by mpsparrow** [comment]
I updated to list. I am pretty sure that is everything that we have agreed on so far. @ronalfy and @szepeviktor: feel free to add anything to the list.

**Comment by mpsparrow** [comment]
I recently did a Disable Updates Manager survey to figure out which features people use the most.
The results are interesting.
![survey question 1](https://cloud.githubusercontent.com/assets/6476699/6542670/c1a218a6-c4cd-11e4-8950-21f51c77f817.png)

**Comment by szepeviktor** [comment]
Please consider not making stats from 5 answers.

**Comment by mpsparrow** [comment]
Yes it is a small amount of people who took the survey but it still shows some results.

**Comment by mpsparrow** [comment]
I don't really think we need this now that the coding is done.
