### ISSUE TITLE
Update German Translation Files

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#61]
I added 5 more strings to fix https://github.com/easy-updates-manager/easy-updates-manager/issues/55

Can you please update the German files if you have time?

**Comment by ronalfy** [comment]
@pixolin

If you have time, can you take a look?

**Comment by mpsparrow** [comment]
I am busy today with a relatives birthday so I can't do it until tomorrow or the day after.
