### ISSUE TITLE
Translation Update

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#64]
Just so that you know. https://make.wordpress.org/plugins/2015/09/01/plugin-translations-on-wordpress-org/

**Comment by ronalfy** [comment]
Thanks! We're good here. Just need to wait for the magic email and we can remove our translations.

Very excited about this.

**Comment by mpsparrow** [comment]
Yes. I would assume both of us will receive the email. Although it may take a while considering that they are going by most active installs (which we only have 30,000+).

I added a separate issue for removing the translation files. https://github.com/easy-updates-manager/easy-updates-manager/issues/65

**Comment by ronalfy** [comment]
Only! Ha.

**Comment by mpsparrow** [comment]
Haha ya. Should say, "it shouldn't take that long because we have 30,000 activate installs".

**Comment by ronalfy** [comment]
Soon to show 40,000+. I'm personally thrilled/happy you allowed me to contribute to this plugin. It's hard now to find a remotely comparable plugin.

**Comment by mpsparrow** [comment]
Well without you this plugin would be nowhere close to what it is today. Before you came along I was having trouble keeping up with all the support and coding to maintain Easy Updates Manager. You have brought an extra level of expertise which has helped push Easy Updates Manager into one of the best, if the best updates manager available for WordPress.
