### ISSUE TITLE
remove translation files

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#65]
Need to wait: https://github.com/easy-updates-manager/easy-updates-manager/issues/64

I am adding this to the 5.2 milestone in hopes that we will be able to remove them by then.

**Comment by mpsparrow** [comment]
Doesn't look like this is going to happen for quite a while (I would guess a few months) so moving to future release.

**Comment by ronalfy** [comment]
Moving to future release since we can't do this for 5.3.0.

**Comment by mpsparrow** [comment]
Easy Updates Manager is up! https://translate.wordpress.org/projects/wp-plugins/stops-core-theme-and-plugin-updates

**Comment by ronalfy** [comment]
@pixolin translations now occur here: https://translate.wordpress.org/projects/wp-plugins/stops-core-theme-and-plugin-updates/
