### ISSUE TITLE
Attempt to figure out third-party plugin/theme automatic updates

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#66]
Attempt to figure out premium plugin/themes updates.

Ideal situation is our plugin handles everything without third-party script having to modify to work with our plugin.

Plugins such as Gravity Forms include their own automatic update feature, for example.

Assuming a solution is found, I'll adjust the milestones as appropriate.

**Comment by mpsparrow** [comment]
Sounds good.

**Comment by ronalfy** [comment]
@mpsparrow I got the Advanced tab to work with a forced cron. Takes about a minute or so depending on the server. 

It _did update Gravity Forms_, but that is the only premium item I can get my hands on.

I also updated the filters.

Want to just push out 5.2 with those two changes and punt the rest to a later milestone?

**Comment by mpsparrow** [comment]
Sure, we can do a 5.2.1 release some time or even just bump the rest of the stuff into a bigger 5.3 release.

**Comment by ronalfy** [comment]
I created a 5.2.1 milestone in case we need it.

**Comment by mpsparrow** [comment]
Awesome! Should be just bump https://github.com/easy-updates-manager/easy-updates-manager/issues/69 to 5.2.1 and release 5.2 now?

**Comment by ronalfy** [comment]
Already done sir.

**Comment by mpsparrow** [comment]
great
