### ISSUE TITLE
Change menu title to "Updates Options"

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#67]
Just a suggestion, but should we change our menu option from "Update Options" to "Updates Options" ?

Not a huge deal and nobody has complained about this if not implemented. 

Rationale would be:
1. Update Options like someone is updating options, like WordPress options in the options database to a dev.
2. Updates (plural version) conforms more to how WordPress names its menus in this section.
3. Updates Options seems clearer.

Also very open for alternative titles.

**Comment by ronalfy** [comment]
If we agree to this, would be nice to get some feedback from nonnative English speakers. I can ping a few people as I have a lot of European/Asian colleagues.

**Comment by mpsparrow** [comment]
Agreed! Updates Options is good.

>  I can ping a few people as I have a lot of European/Asian colleagues. 

That would be great if you could.

**Comment by ronalfy** [comment]
Awesome. I'm going to be fairly busy this week (internal work deadline) and I'm going to WordCamp DFW next weekend, so the soonest I can dive into the 5.2 milestone is in about two weeks.

**Comment by mpsparrow** [comment]
Your speaking at a WordCamp? Awesome!

I don't think we need to rush to release 5.2 seeing as 5.1.1 was just released and has no bugs that we know of. So catch up on that work, and then we can attack 5.2.

**Comment by ronalfy** [comment]
Solved: https://github.com/easy-updates-manager/easy-updates-manager/commit/6d2aa9ce0ac26bc521f9a9c23fd2da44452c1368
