### ISSUE TITLE
Delay/Schedule Automatic Updates

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#68]
I though this may be a ok feature for a future release. I thought of it after seeing this. https://wordpress.org/support/topic/delay-to-auto-update?replies=1

We could add a like stager automatic updates across websites feature of something.

Let me know what you think.

**Comment by ronalfy** [comment]
I responded to the thread. Thanks for being proactive.

**Comment by mpsparrow** [comment]
I should have specified that that thread was not on Easy Updates Manager. It was just a thread on the general support forum.

**Comment by ronalfy** [comment]
Yeah, think this is for a server admin to modify crontab. Not a job for a plugin. Just my 2 cents.

**Comment by mpsparrow** [comment]
Ok
