### ISSUE TITLE
Add/Update New Translations

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#69]
Add/update new translations for the following
- [ ] https://github.com/easy-updates-manager/easy-updates-manager/issues/67
- [ ] https://github.com/easy-updates-manager/easy-updates-manager/issues/58
- [ ] https://github.com/easy-updates-manager/easy-updates-manager/issues/70

We will need to add them for both the German and Formal German.

**Comment by ronalfy** [comment]
Updated POT file with this https://github.com/easy-updates-manager/easy-updates-manager/commit/54ee0a1564493e5caad1d7d82d8e175a42c77a07

**Comment by ronalfy** [comment]
No need for #66, but #58 and #67 need translating.

**Comment by mpsparrow** [comment]
What about the German translation?

**Comment by ronalfy** [comment]
@pixolin are you interested in translating a few strings for us again? @mpsparrow can make you a contrib if you don't want to deal with the pull requests.

**Comment by mpsparrow** [comment]
I will gladly add you as a contributor if you want to continue to help.

**Comment by pixolin** [comment]
I currently attend WordCamp Switzerland and will be back to my desk on Monday. Is it OK, when I get back to you with the translation then? However, it is a great pleasure for me to assist you with a German translation!

**Comment by mpsparrow** [comment]
> Is it OK, when I get back to you with the translation then? 

Sound great! Whenever you can get it done is great!

I am adding you as a contributor with admin rights so that you can commit it instead of just creating pull requests.

**Comment by mpsparrow** [comment]
@pixolin: We are bumping this to the 5.2.1 release that will happen this week sometime.

**Comment by ronalfy** [comment]
Fixed with https://github.com/easy-updates-manager/easy-updates-manager/pull/74 and https://github.com/easy-updates-manager/easy-updates-manager/commit/5d4a2e2d13adfda7bce157fd3a672f76ed173ab4
