### ISSUE TITLE
Plugin Banners

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#7]
- [x] Icon  (128px x 128px, 256px x 256px HiDPI ) (icon-128x128.jpg/png | icon-256x256.jpg/png)
- [x] WordPress.org Banner  (772px x 250px, 1544px x 500px HiDPI) (banner-772x250.jpg/png | banner-1544x500.jpg/png)
- [x] Screenshots
- [x] Video Intro Screenshot (HD)

Screenshots/Icon/Banner should be placed in /assets in SVN after 5.0 launch.

**Comment by mpsparrow** [comment]
I have designs some simple logos off of an online logo maker. Do you think they are professional enough? Like you I am not the artistic type.
![logo small](https://cloud.githubusercontent.com/assets/6476699/6608359/9ac0d888-c81c-11e4-858f-d2d55aff0298.png)
![logo small ori](https://cloud.githubusercontent.com/assets/6476699/6608361/9acc718e-c81c-11e4-91c0-0a747ed9a4ea.png)
![logo full](https://cloud.githubusercontent.com/assets/6476699/6608360/9acb405c-c81c-11e4-9125-8b41ce693e37.png)

**Comment by szepeviktor** [comment]
I know a logo designer for around €30.

**Comment by mpsparrow** [comment]
@szepeviktor: This is a free plugin. We are not looking at spending money to make this plugin. The whole point of the logo is just to be a plain logo to fill the WordPress banner and icon.

**Comment by ronalfy** [comment]
I think it looks cool. I know a designer friend if you want to try that,
but she'll want credit in the readme.

**Comment by mpsparrow** [comment]
I don’t mind giving credit to anyone who is willing to help.

**Comment by szepeviktor** [comment]
@mpsparrow I personally think that I have limited time and limited money.
So if I work 2 hours on this project that is equivalent to €30.

**Comment by szepeviktor** [comment]
basically this plugin is _free_ for the user but not free for us.

**Comment by szepeviktor** [comment]
Maybe I am wrong but I spend my time just like I spend my money.

**Comment by ronalfy** [comment]
@szepeviktor I agree with you, but €30 is an insanely low amount for any design.

The simple fact of the matter, we're all donating our time on this project and releasing this code free and open source on .org.

**Comment by szepeviktor** [comment]
Maybe I am faulty but my money does not worth more than my time.

**Comment by szepeviktor** [comment]
And I feel that my time is not for free at all. It costs €16/hour.

**Comment by szepeviktor** [comment]
He has 200,000+ installs:
https://wordpress.org/plugins/antispam-bee/changelog/
See the time he spent on developing this plugin.

**Comment by szepeviktor** [comment]
I wouldn't refrain from spending money as I don't refrain from spending my time here.

**Comment by szepeviktor** [comment]
What do you think?

**Comment by mpsparrow** [comment]
I think in less @ronalfy wants to do something else I am just going to design a simple logo for now.

**Comment by ronalfy** [comment]
Yeah, I ran it by my designer friend, but she is unfortunately too busy.  The good thing about banners though.. we can always change them :D

**Comment by mpsparrow** [comment]
I will just make a plain version of the stuff so that we can update the plugin and then when your designer friend is available she can design the stuff.

**Comment by ronalfy** [comment]
Sure thing.  Just keep in mind on the banner that .org will overlay the plugin name.  So maybe just the vector you have?

For the video, I can just use the graphic and add the plugin name beneath it.

Do you happen to have a dropbox that we can stash files in, or something else in mind perhaps?

**Comment by mpsparrow** [comment]
You mean these?
![banner-772x250](https://cloud.githubusercontent.com/assets/6476699/6631110/708dbf14-c8f7-11e4-9351-255fa7ba0833.png)
![icon-128x128](https://cloud.githubusercontent.com/assets/6476699/6631111/71ee6afc-c8f7-11e4-8454-199710f2dbde.png)

**Comment by mpsparrow** [comment]
Also, I don't have a dropbox account. I could make one.

**Comment by ronalfy** [comment]
How about something like this?  http://www.shutterstock.com/pic-236431474/stock-vector-cloud-computing-refresh.html?src=Q9QvGyhuMdXkmuzuawmBVA-3-36

I don't mind getting it.  I can easily make a banner / icon out of that.

**Comment by mpsparrow** [comment]
That looks good.

**Comment by mpsparrow** [comment]
Did you look into getting it?

**Comment by ronalfy** [comment]
I'll try to look into this today.  I need a break from my sprint :)

I'll set up a dropbox folder and invite you to it.

**Comment by mpsparrow** [comment]
Ok, good job today!

**Comment by ronalfy** [comment]
![easy-updates-manager](https://cloud.githubusercontent.com/assets/636521/6701890/d4c37fe4-ccf0-11e4-9328-2313c6db4342.png)

I've shared what I've done so far on Dropbox.  Here's a screenshot of what it might look on .org.

Also, here is the icon.

![icon-256x256](https://cloud.githubusercontent.com/assets/636521/6701912/1b5f61b6-ccf1-11e4-8369-1714962b1ce0.png)

**Comment by mpsparrow** [comment]
That looks awesome!

**Comment by mpsparrow** [comment]
Just got into Dropbox to view the rest of them. I say that it looks very professional.

**Comment by ronalfy** [comment]
Cool, thanks.  My voice is shot (coming down with a cold), so I will try to do some videos this weekend.

One thought I have is to do just a general video with no narration, so perhaps we can find a Creative Commons track we can use as background music.

**Comment by ronalfy** [comment]
![plugin-hd](https://cloud.githubusercontent.com/assets/636521/6722478/04fb021a-cda8-11e4-94d8-6184f310b82e.png)

This is my proposal for the video intro.  Visby typeface.  Red all in your face :D

**Comment by ronalfy** [comment]
I also pushed some screenshots into Dropbox and updated the readme.  Please let me know what you think.

**Comment by mpsparrow** [comment]
Awesome screenshots. Also the video intro picture is good.

We should have an introduction/promotional video along with then having tutorial videos on how to use the plugin.

Are you going to upload the videos onto YouTube? If so you can select some background music for it when uploading it to YouTube.

Keep up the good work!

> Add music
> 
> You can add a new audio track to your video. Click the music note button in the upper left of the editor to bring up YouTube's library of pre-approved songs.
> 
> Browse the tracks by searching or filtering by artist and genre. When you've found a song you like, drag it to the timeline. Multiple tracks can be added to a project by dragging the song into the timeline.
> 
> Songs, like clips, can't overlap - they can only come before or after each other.
> 
> The audio from an added track will overlap replace your clips’ original audio by default. To customize the volume at which an audio track plays over your clips, adjust the volume slider to at the far right of the name of the track to your preferred setting.

**Comment by mpsparrow** [comment]
Since we have all the pictures I am going to close this. We have an issue already open for the video so we can continue there.
