### ISSUE TITLE
add more personalized admin notice

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#70]
When you click the Force Updates setting the notice should same more then just Options Saved. Maybe something like "updates forced -  wait about 60 seconds, and refresh to test the automatic updates".

**Comment by ronalfy** [comment]
k, I'll see what I can do.

**Comment by mpsparrow** [comment]
Since https://github.com/easy-updates-manager/easy-updates-manager/issues/69 is not getting done until Monday or Tuesday do you think we can fit this in 5.2?

**Comment by ronalfy** [comment]
https://github.com/easy-updates-manager/easy-updates-manager/commit/5c891a7c5a28956cc79d7e61791d98b9e15c99e0

**Comment by mpsparrow** [comment]
Awesome!
