### ISSUE TITLE
Release 5.2.0

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#73]
Need some sanity testing. 

I've done my part. If you have time, just do a quick run-through and we can get this out today.

**Comment by ronalfy** [comment]
@mpsparrow if you can help out would be much appreciated.

**Comment by mpsparrow** [comment]
Sure, I have a few minutes now and then I need to run out. But I will be back in an hour or two and can do some more.

**Comment by ronalfy** [comment]
No worries. If you're comfortable with a quick breeze through, I'll go ahead and deploy it.

**Comment by mpsparrow** [comment]
Sure. I will run through the checklist when I get back. Hopefully I will only be gone an hour or two so we can release this evening.

**Comment by ronalfy** [comment]
Roger that. I'll be around then. Thanks for the help!

**Comment by mpsparrow** [comment]
Thanks for your help.

Just so that you know I added @pixolin to have committing rights. That way he doesn't have to do pull request.

Have to run out the door now.

**Comment by ronalfy** [comment]
Thanks @pixolin! Now try not to break anything. No pressure!

**Comment by mpsparrow** [comment]
Ok, I am back. Time for testing.

**Comment by ronalfy** [comment]
Great. Just let me know when to pull the trigger.

**Comment by mpsparrow** [comment]
will do

**Comment by mpsparrow** [comment]
All appears to be well with 5.2.0. All that needs to be done is the readme.txt changelog for 5.2.0 needs to be added and then I think you can pull the trigger.

**Comment by ronalfy** [comment]
Ok! Thiught I did that already. Checking.

**Comment by mpsparrow** [comment]
looks like you did

**Comment by mpsparrow** [comment]
must of just missed it

**Comment by ronalfy** [comment]
Cool. Pulling trigger. Thanks for the help.

**Comment by mpsparrow** [comment]
no problem

**Comment by ronalfy** [comment]
It's alive: https://wordpress.org/plugins/stops-core-theme-and-plugin-updates/changelog/

**Comment by mpsparrow** [comment]
party!

**Comment by mpsparrow** [comment]
We will see if anybody has any problems but from the looks for things I don't think we will need a 5.2.1.

**Comment by ronalfy** [comment]
Yeah, just a "just in case" release. Props @pixolin for getting us the translations. We know you're busy!

Thanks so much.

**Comment by mpsparrow** [comment]
Yes thank you very much @pixolin!

**Comment by mpsparrow** [comment]
Downloads are skyrocketing! 8.3% (about 2,500 people) are on 5.2.0 at the moment. And 700 downloads in the last two and a half hours.

**Comment by ronalfy** [comment]
Epic!

I just realized we are in the Resources section on this page. Something you added? https://codex.wordpress.org/Configuring_Automatic_Background_Updates

**Comment by mpsparrow** [comment]
Yes actually. I added that in because it was appropriate.

**Comment by ronalfy** [comment]
Ha, awesome.

**Comment by mpsparrow** [comment]
Still waiting for the active downloads to bump up to 40,000+

**Comment by ronalfy** [comment]
Yeah, it's super crazy how popular this plugin is. As far as I know, we're
the only plugin that provides granular control to just about anything
update-related.
