### ISSUE TITLE
Dashboard WireFrame

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#76]
Let's aim for Jetpack's new Dashboard as far as looks go. 

![dashboard](https://cloud.githubusercontent.com/assets/636521/9977860/ee151246-5edb-11e5-9da2-bf29633df5f8.jpg)

**Comment by mpsparrow** [comment]
Something like that design would look very nice. We could add our logo in the background and then have the quick settings to select.

**Comment by ronalfy** [comment]
Box One - Global update options (whether updates are on or off). Includes plugins.
Box Two - Tab/View of Plugin/Theme Updates Disabled (on/off switches)
Box Three -  Tab/View of Plugin/Theme automatic Updates Enabled (on/off switches)
Box Four - Email Notifications (on/off switches)
