### ISSUE TITLE
Update POT Translation for 5.3

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#80]

**Comment by pixolin** [comment]
Hm, there seems to be some issue in the process of creating the translation template (.pot-file), as you again missed out the plugin description.

To add that text string to the translation template, I usually help myself by creating a nonsense-function:

```
function delete_me() {
  $to_be_translated = __( 'Manage and disable WordPress updates, including core, plugin, theme, and automatic updates - Works with Multisite.', 'stops-core-theme-and-plugin-updates' );
} 
```

Once the .pot-file has been created, I delete that little helper.

Of course, this is just a workaround. I've asked Dominik Schilling (@ocean90) how to do it right and he pointed me to https://core.trac.wordpress.org/browser/trunk/tools/i18n/makepot.php, which should create the .pot-file without the need of the function above. Codex covers some [information how to use it](https://codex.wordpress.org/I18n_for_WordPress_Developers#Using_the_i18n_tools), but I must admit I had problems using it – hence the workaround.

**Comment by ronalfy** [comment]
If it's okay, I'll leave POT generation to you. Once kanguage lacks come, these will no longer be issies.

**Comment by pixolin** [comment]
Well, they don't come, they are here already. :) 

(In fact I talked to Petya Raykovska, head of the polyglots group, during WordCamp Zurich and she told me, we are actually doing it wrong and should use translate.wordpress.org instead.)

**Comment by mpsparrow** [comment]
It will be nice once Easy Updates Manager gets on translate.wordpress.org.

**Comment by pixolin** [comment]
Well, I believe I have good news for you! 

Just contacted the polyglots and immediately received some reply by Sam Siedler. Let me just paste what he said:

---

sam [18:55] 
Perfect! We’re importing plugins in batches, based on active users.
The next batch will be imported this week and covers through ~70k active installs.
I ​_believe_​ your plugin will be in the batch after that.

pixolin [18:56] 
Ah, that’s pretty cool! Great!

sam [18:56] 
We email plugin authors before importing them into translate.wordpress.org.
So it looks like @kidsguide and @ronalfy will be the ones emailed.

pixolin [18:57] 
Sounds perfect!

sam [18:57] 
When the import happens is subject to change, _but I’m pretty sure we can get that plugin in the next batch_, depending on how this week’s batch goes. :simple_smile:

---

How does that sound? 

Imagine all the countries you can visit to see your plugin in the local language then. :laughing:

**Comment by mpsparrow** [comment]
Sounds awesome! So me and @ronalfy will be notified when it happens. I believe I made a issue a while back to remove the translation files #65.

**Comment by ronalfy** [comment]
https://github.com/easy-updates-manager/easy-updates-manager/commit/df64a474bc8b00277012556e56f4ded84b8c77ba
