### ISSUE TITLE
Testing for 5.3

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#82]
Testing for 5.3 new features on Mobile, Multisite, and Single Site.

**Comment by pixolin** [comment]
While working on the translation, I saw a _Notice:_ Undefined index: automatic_plugin_updates in /srv/www/easy/htdocs/wp-content/plugins/easy-updates-manager/includes/MPSUM_Admin_Dashboard.php on line 386
