### ISSUE TITLE
New Video

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#83]
I added a new video because I now have a better mic.

I've already updated on .org, but I think it's YouTube's issue that the video is not embedding properly.

I'm going to give it an hour before I panic. 

https://www.youtube.com/watch?v=V8AWwBc6GrU&feature=youtu.be

**Comment by mpsparrow** [comment]
I appears to be embedded right in the readme.txt so I don't know what it could be.

**Comment by ronalfy** [comment]
YouTube says to wait 30!mins an hour.!

**Comment by mpsparrow** [comment]
Try [youtube https://www.youtube.com/watch?v=V8AWwBc6GrU]

**Comment by ronalfy** [comment]
Thanks, that did the trick. THANKS!

**Comment by mpsparrow** [comment]
Awesome!
