### ISSUE TITLE
One star rating modlook

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#84]
Left a modlook tag here: https://wordpress.org/support/topic/crap-breaks-backend?replies=3

We'll see if anything happens. Using swear words in the forum is a big no-no.

**Comment by mpsparrow** [comment]
They appeared to have removed it. I have spent time in the forums though and they don't care if they swear as long as it isn't horrible and insulting someone.

**Comment by ronalfy** [comment]
Yah, nothing we can do about it. Eh.

**Comment by mpsparrow** [comment]
sadly no

**Comment by mpsparrow** [comment]
It is really annoying when people leave one star reviews like and then don't reply.

**Comment by ronalfy** [comment]
Yuppers.

**Comment by mpsparrow** [comment]
But forum mods don't like to remove them because they are still legit reviews.
