### ISSUE TITLE
Dashboard Tab and Windows Edge Browser Conflict

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#87]
The dashboard tab and the Windows 10 Edge browser don't appear to be getting along.

Edge Browser
![screenshot 2015-09-27 15 04 25](https://cloud.githubusercontent.com/assets/6476699/10124765/50127af6-652b-11e5-98c2-fd9c92331702.png)

What Firefox, Chrome, Windows Safari, and Internet Explorer show.
![screenshot 2015-09-27 15 06 46](https://cloud.githubusercontent.com/assets/6476699/10124766/57fc1132-652b-11e5-8f04-5aeee3834ad7.png)

Also the Edge Browser shows a notice every time you click on a setting.
![screenshot 2015-09-27 15 14 55](https://cloud.githubusercontent.com/assets/6476699/10124767/69ac7cdc-652b-11e5-8b48-2f47df0c5e5a.png)

And, the boxes are out of alignment.

**Comment by ronalfy** [comment]
Just tried it on edge. Worked perfectly.
