### ISSUE TITLE
Readme.md Docs

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#9]
Add readme.md docs and/or wiki docs

**Comment by mpsparrow** [comment]
I am planning to set up the GitHub wiki and not include the readme.md in the WordPress.org version. The readme.md on GitHub will just give a quick outline of the plugin and point you to WordPress.org and the GitHub wiki. Do you think this is ok?

**Comment by szepeviktor** [comment]
https://github.com/xwp/wp-dev-lib

**Comment by ronalfy** [comment]
Sounds great. I have a bash script that I run on my local git to commit to
WordPress svn, so it'll ignore all the git stuff. For the first 5.0 version
though, I think it'll be better if we did a manual svn release. I guess
we'll cross that bridge when we come to it :)

**Comment by mpsparrow** [comment]
When we finish this plugin I will happily give you admin access to the plugin on WordPress.org. That way you can submit 5.0 if you would like.

**Comment by ronalfy** [comment]
No pressure :D - only 10,000+ installs to worry about..

But the features that are in there now are game changing.

**Comment by mpsparrow** [comment]
It would be nice if that number went up with version 5.0.

**Comment by mpsparrow** [comment]
Done

**Comment by ronalfy** [comment]
Just saw this today. WordPress.org is now showing 20,000+ installs.

**Comment by mpsparrow** [comment]
Noticed the same thing just a few hours ago.
