### ISSUE TITLE
Roary Sassifies our CSS and Makes Dashboard Better

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#91]

**Comment by ronalfy** [comment]
Just a quick note @mpsparrow that Roary is making very good progress with Dashboard styles. I'll let you know when they're done and you can check out the dev branch.

**Comment by mpsparrow** [comment]
Awesome! Looking forward to seeing it.

**Comment by ronalfy** [comment]
Styles are in DEV, but they are still a WIP. I have to do some re-structuring.

Let's plan on a weekend release of 5.3.3.

**Comment by ronalfy** [comment]
@roarytubbs wants the main 3 tabs on line line (like in Jetpack) and the remaining two in a different row.

**Comment by mpsparrow** [comment]
Ok, sounds good.

**Comment by ronalfy** [comment]
@roarytubbs I made the structural changes and fixed the JS tab errors. If you could finish up the styles, we'd like to get this updated Saturday.

We're all volunteers, so if it can't make it this weekend, let us know. There is nothing pressing, just an internal goal.

**Comment by ronalfy** [comment]
@mpsparrow if you check out the dev branch you'll see where we're going with this. It looks great. Just needs one more final push.

**Comment by mpsparrow** [comment]
Awesome. I have already checked it out and it looks amazing.

**Comment by ronalfy** [comment]
@mpsparrow We've made some more progress with styles. I had to strip out some JS, but I think it still works fine. I'll tackle the JS in a 5.3.4 or something.

Can you take a look? And if it looks great, let's push out 5.3.3 this weekend.

**Comment by ronalfy** [comment]
@roarytubbs will take a look tomorrow as a sanity test.

**Comment by mpsparrow** [comment]
Awesome! I will take a look tonight or tomorrow morning.

**Comment by mpsparrow** [comment]
Just took a look at it now. It looks way better.

**Comment by ronalfy** [comment]
I agree. It's pretty clear a lot of work went into the updates.

I do front-end dev, I'm more of a back-end coder.

**Comment by ronalfy** [comment]
Closing as @roarytubbs is done styling and I am done with JS.
