### ISSUE TITLE
Translate the Plugin in Glotpress

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#94]
I am trying to get us contributor rights so that we can translate the plugin. @ronalfy and @pixolin 
Hopefully they will process this soon so that we can translate the plugin completely in German and English (Canada).

https://make.wordpress.org/polyglots/2015/10/08/howdy-polyglots-i-am-the-plugin-author-for-5/

**Comment by pixolin** [comment]
Your request has immediately been taken care of and I already could add translation strings _and_ approve them. Yay. (German translation 100% up to date btw. and a bunch of other translations already being worked on as it seems.)

**Comment by ronalfy** [comment]
Nice! I just got one of my installs to auto-install the German language pack. Kudos.

**Comment by mpsparrow** [comment]
Awesome! Thanks @pixolin. We should probably translate the Development Readme and Stable Readme too.

I am working on translating to English (Canada).

**Comment by ronalfy** [comment]
I'm still not sure: trunk should always be stable; but for a lot of plugin
we provide the stable tag.

**Comment by pixolin** [comment]
@mpsparrow Oh, absolutely! When i said, German translation is 100%, I was actually talking about the strings used in the php-files, not the readme-file, which certainly needs some more love in the German translation. Work in progress :smile:

**Comment by mpsparrow** [comment]
Awesome! Thanks for all your help.

**Comment by mpsparrow** [comment]
Almost done the English (Canada) translation!

**Comment by mpsparrow** [comment]
English (Canada) translation done. I am now also a editor for English (Canada) so I can push any changes without it being reviewed.

**Comment by mpsparrow** [comment]
English (Canada) is live as of yesterday. Now all that needs to be done is the German development and stable readme translations.

**Comment by pixolin** [comment]
Oh well, always those lazy Germans… ;) 
Added the translation for the readme file today.

**Comment by mpsparrow** [comment]
Awesome! Thanks for all your help.
