### ISSUE TITLE
Fix Hebrew Banner

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#95]
The Hebrew (and other right to left languages) need to have a mirrored banner so that you can see the cloud image. https://make.wordpress.org/polyglots/2015/10/08/howdy-polyglots-i-am-the-plugin-author-for-5/#comment-270092

**Comment by mpsparrow** [comment]
Also there is a meta ticket for this. https://meta.trac.wordpress.org/ticket/757

**Comment by mpsparrow** [comment]
Trying to fix this right now.

**Comment by mpsparrow** [comment]
I am putting this on hold as there is currently no support for this. In less we create a plugin banner that works with both right and lift aligned text, the only thing me can do is wait until they add support for it.

For now I added a rtl banner. This way when they add the support for it it will already be there.

**Comment by ronalfy** [comment]
I'll get my designer co-worker to look at this on Wednesday to see if there
is a good solution.

**Comment by ronalfy** [comment]
@mpsparrow I saw your RTL assets and they look fantastic. This Wednesday when Roary and I work on the plugin, I'll see if he can create a banner that will work until core gets their act together. What say you?

We have all the original assets in Dropbox, so I'll run any fixes on this issue.

**Comment by mpsparrow** [comment]
We could use a banner that works with both. For now I added the banners because hopefully they will get there act together and fix the problem (https://meta.trac.wordpress.org/ticket/757). A quick fix for now would be if a banner was redesigned to work with both.

**Comment by mpsparrow** [comment]
Just a quick update. It looks like the RTL banners for the WordPress.org directory will be soon. On the other hand I don't know about the RTL banners for the admin popups. So it is probably a good option to redesigned the banners to work with both left and right text. Although if you think that is a waste of time we can also just leave it.

**Comment by ronalfy** [comment]
Let me get back to you tomorrow. Maybe Roary can figure it out so we can
just have one banner.

**Comment by ronalfy** [comment]
Roary is making good progress on this. We'll share results when he is finished.

**Comment by mpsparrow** [comment]
Awesome! Looking forward to seeing them.

**Comment by roarytubbs** [comment]
![easy-updates-manager-example-banner](https://cloud.githubusercontent.com/assets/1294345/10801102/a3e9493c-7d83-11e5-9398-951a9f629605.jpg)

**Comment by ronalfy** [comment]
@mpsparrow what do you think of the above? I think it looks fantastic.

**Comment by mpsparrow** [comment]
Hey @roarytubbs! That looks awesome. I say we add it to Dropbox and then commit it in 5.3.3.

**Comment by ronalfy** [comment]
We don't need a separate update for the banners though. Can you do an SVN replacement? Roary will add the banners to dropbox shortly.

**Comment by mpsparrow** [comment]
Your right. I will SVN replace them ASAP.

**Comment by ronalfy** [comment]
Okay, Roary just pushed them to dropbox. Feel free to update the assets when ready sir.

**Comment by ronalfy** [comment]
His .org username is roary86. I'll add him to the readme as soon as I can if you think that is appropriate. 

I want to push out 5.3.3 when my ticket is committed and Beta 2 comes out.

**Comment by mpsparrow** [comment]
Yes, add him to the readme.

**Comment by ronalfy** [comment]
Okay, I'm going to create a separate issue for that so I don't forget.

**Comment by mpsparrow** [comment]
Just uploaded the new banners. Should show in a second.

**Comment by mpsparrow** [comment]
It is up and displaying nicely.

**Comment by ronalfy** [comment]
Very well done all.
