### ISSUE TITLE
Add Advanced Setting to Remove Dashboard Tab

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#96]
Although lots of people are sure to like the new Dashboard tab I am sure that there are some people out there that don't like it. For this reason I think a setting should be added in the Advanced tab allowing you to remove the Dashboard tab. Do you think this is worth it @ronalfy?

**Comment by ronalfy** [comment]
Decisions, not options :)

Have you heard anybody nay say it yet?

**Comment by mpsparrow** [comment]
I have gotten a mixed reaction in a random email.

**Comment by ronalfy** [comment]
Oh ok. I'd lean filter here than option, since it'll likely be an advanced
user who hates it. I've gotten several reviews of positive feedback
personally. I try to avoid the "lets do an option cause we can motto".

**Comment by mpsparrow** [comment]
Ok, agreed.
