### ISSUE TITLE
Typo in readme.txt?

### ISSUE THREAD

**Issue by pixolin** [easy-updates-manager/easy-updates-manager#97]
While working on German translation of the readme.txt, I stumbled upon one phrase which doesn't seem to make sense. Can someone please confirm, whether [line 27 of readme.txt](https://github.com/easy-updates-manager/easy-updates-manager/blob/trunk/readme.txt#L27) is correct? Shouldn't it instead be 

_Translation Updates - This setting can unable automatic updating_ **of** _translation updates._

**Comment by mpsparrow** [comment]
I think it should be

> This setting can unable automatic updating for translation updates.

I will change it right now.

**Comment by pixolin** [comment]
OK, then my translation of that string is correct. 
Guess it will pop up with the next version anyway if the string gets altered.

**Comment by mpsparrow** [comment]
Yep. Thanks for noticing that.
