### ISSUE TITLE
Plugin/theme/translation update emails being sent

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#99]
Pushing code shortly to resolve this.

**Comment by ronalfy** [comment]
Can't pin this down. I committed some code to dev, but it didn't fix it. I need to figure out if it's a Beta bug, or our bug. It appeared very apparently it was our code, so still investigating.

**Comment by mpsparrow** [comment]
Great! Let me know if I can do anything.

**Comment by ronalfy** [comment]
Once I nail this down, may need help testing the translation update emails. I'll let you know.

**Comment by ronalfy** [comment]
Yes, WordPress bug and EUM bug. I fixed the EUM bug with https://github.com/easy-updates-manager/easy-updates-manager/commit/5044eba204a8f1db6bbedcdc4b9fdd2073f74e1b

**Comment by ronalfy** [comment]
Will have to write a new patch and get it submitted.

**Comment by mpsparrow** [comment]
ok, once again let me know if I can do anything to help.

**Comment by ronalfy** [comment]
No rush unless we can get this ticket approved. Then I can test against trunk and double-check on Beta 2.  

Here's the ticket. https://core.trac.wordpress.org/ticket/34434

**Comment by ronalfy** [comment]
This code is going into 5.4, so closing. Will create a new ticket if changes don't make it into core.
